content = open(r"D:\my-projects\agent-monitor\viewer.py", encoding="utf-8").read()
lines = content.splitlines()
import re
markers = [
    ("view_mode init", "st.session_state.setdefault(\"view_mode\""),
    ("expanded_spans init", "st.session_state.setdefault(\"expanded_spans\""),
    ("_mermaid_safe_id def", "def _mermaid_safe_id"),
    ("_render_tree def", "def _render_tree("),
    ("_render_metadata_panel def", "def _render_metadata_panel("),
    ("old _render_msg", "def _render_msg(role: str, content: object)"),
    ("_render_run_tab def", "def _render_run_tab("),
    ("_render_input_fallback def", "def _render_input_fallback("),
    ("left tree section", "LEFT tree renderer"),
    ("right meta panel css", "right metadata panel"),
    ("col_tree = st.columns", "col_tree, col_detail, col_meta = st.columns"),
    ("input block", "Input block (collapsible)"),
    ("output block", "Output block (collapsible)"),
    ("Feedback tab", "No feedback recorded yet"),
    ("Error", "Stack trace"),
    ("Identity detail", "Identity</div>"),
    ("Timing detail", "Timing</div>"),
    ("All attrs", "All attributes (filtered)"),
    ("Span events", "Span events</div>"),
    ("Tokens meta", "meta-section\"><h5>Tokens</h5>"),
    ("Cost meta", "meta-section\"><h5>Cost (est.)</h5>"),
    ("Selected meta", "meta-section\"><h5>Selected span</h5>"),
    ("no token", "no token data captured"),
    ("click tree", "click a tree node"),
    ("Service kpi", "\"Service\", trace_kpi.service_name"),
    ("LLM/Tool kpi", "\"LLM / Tool\""),
    ("Chain/Agent kpi", "\"Chain / Agent / Prompt\""),
    ("No spans", "No spans in the current trace"),
    ("Once score", "Once you score"),
    ("Parent Span", "\"Parent Span ID\""),
    ("Service span", "\"Service\", span.get"),
    ("Schema ver", "\"Schema ver\""),
    ("Session/Thread", "\"Session / Thread\""),
    ("User", "\"User\", uid"),
    ("Tags", "\"Tags\", str(tags)"),
    ("Tags joined", "\"Tags\", \", \".join(str(t)"),
    ("Duration", "\"Duration\""),
    ("Name", "\"Name\", name"),
    ("Kind", "\"Kind\", kind"),
    ("Latency", "\"Latency\""),
    ("Input tokens", "\"Input tokens\""),
    ("Output tokens", "\"Output tokens\""),
    ("Total tokens", "\"Total tokens\""),
    ("Cache read", "\"Cache read tokens\""),
    ("Reasoning", "\"Reasoning tokens\""),
    ("Nav Tree", "Navigation Tree"),
    ("Flow state", "Flow state ("),
    ("Click tree", "Click a node in the tree"),
    ("In/Out", "<div class=\"k\">In / Out</div>"),
    ("max-height", "max-height: 6em"),
    ("Agent monitor", "Agent Trace Monitor"),
    ("Tabs Run", "st.tabs([\"Run\""),
    ("Trace source", "\"Trace source\""),
    ("Input Input", "Input"),
    ("Output Output", "Output"),
    ("Tool arguments", "Tool arguments"),
    ("Stack trace", "**Stack trace:**"),
    ("no parameters", "(no parameters captured)"),
    ("no result", "(no result captured)"),
    ("no events", "(no span events recorded)"),
    ("Once score raw", "Once you score"),
    ("Feedback yes", "No feedback recorded yet"),
    ("tabs[2] meta", "with tabs[2]:"),
    ("Agent error", "#### \u26a0 Error"),
    ("Identity", "Identity</div>"),
]
for label, needle in markers:
    idx = content.find(needle)
    if idx >= 0:
        line = content[:idx].count(chr(10)) + 1
        print("  L" + str(line) + ": " + label)
    else:
        print("  MISSING: " + label)