# -*- coding: utf-8 -*-
"""Phase 3: insert flowchart helpers (including all the new fixes)."""
import sys
sys.stdout.reconfigure(encoding="utf-8")

p = r"D:\my-projects\agent-monitor\viewer.py"
content = open(p, encoding="utf-8").read()

helpers_marker = "# LEFT tree renderer"
assert helpers_marker in content

# All helpers including the latest fixes (chain/parallel inference, focusSpan with window.top, etc.)
helpers = (
    "# ---------------------------------------------------------------------------\n"
    "# Flowchart mode (Mermaid) + click-to-zoom\n"
    "# ---------------------------------------------------------------------------\n"
    "_MERMAID_MAX_NODES = 80\n"
    "_NODE_LABEL_MAX_CHARS = 60\n"
    "\n"
    "\n"
    "def _mermaid_safe_id(sid):\n"
    "    return 'n_' + sid.replace('-', '_')\n"
    "\n"
    "\n"
    "def _mermaid_label(span):\n"
    "    attrs = span.get('attributes') or {}\n"
    "    kind = span_kind(attrs)\n"
    "    info = SPAN_KINDS.get(kind, SPAN_KINDS['UNKNOWN'])\n"
    "    icon = info[0]\n"
    "    name = _span_display_name(span)\n"
    "    name = re.sub(r'[\\\"\\\\#;|]', ' ', name).strip()\n"
    "    if len(name) > _NODE_LABEL_MAX_CHARS:\n"
    "        name = name[:_NODE_LABEL_MAX_CHARS - 1] + '...'\n"
    "    start_ns = int(span.get('start_time', 0))\n"
    "    end_ns = int(span.get('end_time', 0))\n"
    "    dur_ms = (end_ns - start_ns) / 1_000_000\n"
    "    dur = _format_duration_ms(dur_ms)\n"
    "    return f'<b>{icon} {name}</b><br/><small>{kind} &middot; {dur}</small>'\n"
    "\n"
    "\n"
    "def _build_mermaid(spans, *, focus=None, hops=2):\n"
    "    \"\"\"Build a Mermaid `flowchart TD` source. With focus, render a 2-hop subgraph.\"\"\"\n"
    "    if not spans:\n"
    "        return 'flowchart TD\\n    empty[\\u3000\\uff08\\u65e0 span\\uff09\\u3000]'\n"
    "    spans_by_id = {s['span_id']: s for s in spans}\n"
    "\n"
    "    if focus and focus in spans_by_id:\n"
    "        visible = {focus}\n"
    "        up, down = {focus}, {focus}\n"
    "        for _ in range(hops):\n"
    "            new_up = set()\n"
    "            for sid in up:\n"
    "                pid = spans_by_id.get(sid, {}).get('parent_span_id')\n"
    "                if pid and pid in spans_by_id and pid not in visible:\n"
    "                    new_up.add(pid)\n"
    "            visible |= new_up\n"
    "            up = new_up\n"
    "            new_down = set()\n"
    "            for sid in down:\n"
    "                for s in spans:\n"
    "                    if s.get('parent_span_id') == sid and s['span_id'] not in visible:\n"
    "                        new_down.add(s['span_id'])\n"
    "            visible |= new_down\n"
    "            down = new_down\n"
    "    else:\n"
    "        visible = {s['span_id'] for s in spans}\n"
    "    visible_spans = [s for s in spans if s['span_id'] in visible]\n"
    "\n"
    "    if len(visible_spans) > _MERMAID_MAX_NODES and not focus:\n"
    "        return (\n"
    "            'flowchart TD\\n'\n"
    "            '    root[<\\u3000\\u5171 ' + str(len(spans)) + ' \\u4e2a span\\u3000<br/>'\n"
    "            \"<small>\\u8282\\u70b9\\u6570\\u8fc7\\u591a\\uff0c\\u8bf7\\u5207\\u56de \\u5217\\u8868 \\u6a21\\u5f0f\\u67e5\\u770b</small>]\\n\"\n"
    "            '    classDef root fill:#4b5563,color:#fff,stroke:#1f2937;\\n'\n"
    "            '    class root root;'\n"
    "        )\n"
    "\n"
    "    visible_spans.sort(key=lambda s: int(s.get('start_time', 0)))\n"
    "    starts = [int(s.get('start_time', 0)) for s in visible_spans]\n"
    "    min_start = min(starts) if starts else 0\n"
    "\n"
    "    out = ['flowchart TD']\n"
    "    out.append('    classDef llm       fill:#1d4ed8,color:#fff,stroke:#1e3a8a,stroke-width:1px;')\n"
    "    out.append('    classDef chain     fill:#065f46,color:#fff,stroke:#064e3b,stroke-width:1px;')\n"
    "    out.append('    classDef tool      fill:#b45309,color:#fff,stroke:#7c2d12,stroke-width:1px;')\n"
    "    out.append('    classDef agent     fill:#a16207,color:#fff,stroke:#713f12,stroke-width:1px;')\n"
    "    out.append('    classDef retriever fill:#7e22ce,color:#fff,stroke:#581c87,stroke-width:1px;')\n"
    "    out.append('    classDef embedding fill:#0e7490,color:#fff,stroke:#164e63,stroke-width:1px;')\n"
    "    out.append('    classDef reranker  fill:#6d28d9,color:#fff,stroke:#4c1d95,stroke-width:1px;')\n"
    "    out.append('    classDef prompt    fill:#3f6212,color:#fff,stroke:#365314,stroke-width:1px;')\n"
    "    out.append('    classDef parser    fill:#4b5563,color:#fff,stroke:#1f2937,stroke-width:1px;')\n"
    "    out.append('    classDef evaluator fill:#a8a29e,color:#1c1917,stroke:#78716c,stroke-width:1px;')\n"
    "    out.append('    classDef guardrail fill:#b91c1c,color:#fff,stroke:#7f1d1d,stroke-width:1px;')\n"
    "    out.append('    classDef unknown   fill:#6b7280,color:#fff,stroke:#374151,stroke-width:1px;')\n"
    "    out.append('    classDef error     stroke:#ef4444,stroke-width:2px,color:#fff;')\n"
    "    out.append('    classDef focus     stroke:#facc15,stroke-width:3px;')\n"
    "    out.append('    linkStyle default stroke:#64748b,stroke-width:1px;')\n"
    "\n"
    "    children_by_parent = {}\n"
    "    for s in visible_spans:\n"
    "        pid = s.get('parent_span_id')\n"
    "        if pid and pid in visible:\n"
    "            children_by_parent.setdefault(pid, []).append(s)\n"
    "\n"
    "    _handled_parents = set()\n"
    "\n"
    "    for span in visible_spans:\n"
    "        sid = span['span_id']\n"
    "        nid = _mermaid_safe_id(sid)\n"
    "        kind = span_kind(span.get('attributes') or {})\n"
    "        kind_class = kind.lower() if kind in SPAN_KINDS else 'unknown'\n"
    "        cls = [kind_class]\n"
    "        if str(span.get('status', '')).upper() == 'ERROR':\n"
    "            cls.append('error')\n"
    "        if sid == focus:\n"
    "            cls.append('focus')\n"
    "        start_ns = int(span.get('start_time', 0))\n"
    "        offset_ms = int((start_ns - min_start) / 1_000_000)\n"
    "        label = _mermaid_label(span)\n"
    "        full_label = f\"{label}<br/><small>t+{offset_ms}ms</small>\"\n"
    "        safe = re.sub(r'[\\\"\\\\#;|]', ' ', full_label).strip()\n"
    "        out.append(f'    {nid}[\\\"{safe}\\\"]')\n"
    "        out.append(f'    class {nid} {\",\".join(cls)};')\n"
    "\n"
    "    for parent_id, kids in children_by_parent.items():\n"
    "        if len(kids) < 2:\n"
    "            continue\n"
    "        sorted_kids = sorted(kids, key=lambda s: int(s.get('start_time', 0)))\n"
    "        n_kids = len(sorted_kids)\n"
    "        all_sequential = True\n"
    "        for i in range(n_kids - 1):\n"
    "            prev_end = int(sorted_kids[i].get('end_time', 0))\n"
    "            next_start = int(sorted_kids[i + 1].get('start_time', 0))\n"
    "            if next_start < prev_end:\n"
    "                all_sequential = False\n"
    "                break\n"
    "        pnid = _mermaid_safe_id(parent_id)\n"
    "        if all_sequential:\n"
    "            _handled_parents.add(parent_id)\n"
    "            first_id = _mermaid_safe_id(sorted_kids[0]['span_id'])\n"
    "            out.append(f'    {pnid} --> {first_id}')\n"
    "            for i in range(n_kids - 1):\n"
    "                a = _mermaid_safe_id(sorted_kids[i]['span_id'])\n"
    "                b = _mermaid_safe_id(sorted_kids[i + 1]['span_id'])\n"
    "                out.append(f'    {a} --> {b}')\n"
    "        else:\n"
    "            _handled_parents.add(parent_id)\n"
    "            out.append('    subgraph SG_' + pnid + '[\"\\u5e76\\u884c\\u5206\\u652f\"]')\n"
    "            out.append('    direction LR')\n"
    "            for k in sorted_kids:\n"
    "                out.append(f\"        {_mermaid_safe_id(k['span_id'])}\")\n"
    "            out.append('    end')\n"
    "            for k in sorted_kids:\n"
    "                out.append(f'    {pnid} --> {_mermaid_safe_id(k[\"span_id\"])}')\n"
    "\n"
    "    for span in visible_spans:\n"
    "        pid = span.get('parent_span_id')\n"
    "        if pid and pid in visible and pid not in _handled_parents:\n"
    "            out.append(f'    {_mermaid_safe_id(pid)} --> {_mermaid_safe_id(span[\"span_id\"])}')\n"
    "\n"
    "    for span in visible_spans:\n"
    "        nid = _mermaid_safe_id(span['span_id'])\n"
    "        out.append(f'    click {nid} focusSpan')\n"
    "\n"
    "    return '\\n'.join(out)\n"
    "\n"
    "\n"
    "def _render_mermaid_html(src, *, height=620, key_prefix='m'):\n"
    "    \"\"\"Render Mermaid inside an iframe. Mermaid click directive fires\n"
    "    window.focusSpan(nodeId); DOM delegation is kept as a backup.\n"
    "    \"\"\"\n"
    "    js_src = (\n"
    "        src.replace('\\\\\\\\', '\\\\\\\\\\\\\\\\')\n"
    "           .replace('`', '\\\\\\\\`')\n"
    "           .replace('${', '\\\\\\\\${')\n"
    "    )\n"
    "    html_doc = (\n"
    "        '<!DOCTYPE html>\\n'\n"
    "        '<html><head><meta charset=\"utf-8\">\\n'\n"
    "        '<style>\\n'\n"
    "        '  body { margin: 0; padding: 8px; background: transparent;\\n'\n"
    "        \"         color: #e5e7eb; font-family: ui-system, system-ui, sans-serif; }\\n\"\n"
    "        '  .mermaid { background: rgba(255,255,255,0.02); border-radius: 8px; padding: 8px; overflow-x: auto; }\\n'\n"
    "        '  .node { cursor: pointer; }\\n'\n"
    "        '  .node:hover rect, .node:hover polygon { filter: brightness(1.25); }\\n'\n"
    "        '</style>\\n'\n"
    "        '<script src=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js\"></script>\\n'\n"
    "        '</head><body>\\n'\n"
    "        \"<div class='mermaid' id='m_\" + key_prefix + \"'>\\n\"\n"
    "        + js_src + '\\n'\n"
    "        \"</div>\\n\"\n"
    "        \"<script>\\n\"\n"
    "        \"  window.focusSpan = function(nodeId) {\\n\"\n"
    "        \"    var spanId = (nodeId || \\\"\\\").replace(/^n_/, \\\"\\\").replace(/_/g, \\\"-\\\");\\n\"\n"
    "        \"    if (!spanId) return;\\n\"\n"
    "        \"    var url = new URL(window.top.location.href);\\n\"\n"
    "        \"    url.searchParams.set(\\\"focus\\\", spanId);\\n\"\n"
    "        \"    try { window.top.location.href = url.toString(); }\\n\"\n"
    "        \"    catch (e1) { try { window.parent.location.href = url.toString(); } catch (e2) { window.location.href = url.toString(); } }\\n\"\n"
    "        \"  };\\n\"\n"
    "        \"  mermaid.initialize({\\n\"\n"
    "        \"    startOnLoad: true,\\n\"\n"
    "        \"    theme: 'dark',\\n\"\n"
    "        \"    themeVariables: {\\n\"\n"
    "        \"      background: '#0f172a',\\n\"\n"
    "        \"      primaryColor: '#1e293b',\\n\"\n"
    "        \"      primaryTextColor: '#e5e7eb',\\n\"\n"
    "        \"      primaryBorderColor: '#334155',\\n\"\n"
    "        \"      lineColor: '#64748b',\\n\"\n"
    "        \"      fontFamily: 'ui-system, system-ui, sans-serif',\\n\"\n"
    "        \"    },\\n\"\n"
    "        \"    flowchart: { curve: 'basis', htmlLabels: true, useMaxWidth: true },\\n\"\n"
    "        \"    securityLevel: 'loose',\\n\"\n"
    "        \"  }).then(function() {\\n\"\n"
    "        \"    document.querySelectorAll('.mermaid .node').forEach(function(node) {\\n\"\n"
    "        \"      node.addEventListener('click', function() {\\n\"\n"
    "        \"        var id = node.id || (node.querySelector('[id]') ? node.querySelector('[id]').id : '');\\n\"\n"
    "        \"        var m = id.match(/n_[A-Za-z0-9_]+/);\\n\"\n"
    "        \"        if (m) window.focusSpan(m[0]);\\n\"\n"
    "        \"      });\\n\"\n"
    "        \"    });\\n\"\n"
    "        \"  });\\n\"\n"
    "        \"</script>\\n\"\n"
    "        \"</body></html>\"\n"
    "    )\n"
    "    st.components.v1.html(html_doc, height=height, scrolling=True)\n"
    "\n"
    "\n"
    "def _render_flowchart_mode(sel_spans, kpi, all_by_id):\n"
    "    \"\"\"3-column flowchart explorer: traces | mermaid TD | span detail.\"\"\"\n"
    "    _url_trace = st.query_params.get('trace')\n"
    "    if _url_trace and _url_trace in traces:\n"
    "        if st.session_state.selected_trace != _url_trace:\n"
    "            st.session_state.selected_trace = _url_trace\n"
    "            sel_spans = traces[_url_trace]\n"
    "            all_by_id = {s['span_id']: s for s in sel_spans}\n"
    "            kpi = _aggregate_kpi(sel_spans)\n"
    "    focus = st.query_params.get('focus')\n"
    "\n"
    "    col_left, col_center, col_right = st.columns([1.1, 2.5, 1.3])\n"
    "\n"
    "    with col_left:\n"
    "        _render_trace_cards_list()\n"
    "    with col_center:\n"
    "        _render_flowchart_center(sel_spans)\n"
    "    with col_right:\n"
    "        _render_detail_column(sel_spans, all_by_id, focus)\n"
    "\n"
    "\n"
    "def _render_trace_cards_list():\n"
    "    \"\"\"Left column: list each trace as a card.  Click -> switch trace.\n"
    "    Traces are sorted by earliest start_time (oldest first).\n"
    "    \"\"\"\n"
    "    st.markdown('#### \\U0001F4CB Traces')\n"
    "    if not traces:\n"
    "        st.caption('\\u8fd8\\u6ca1\\u6709 trace\\u3002\\u8bf7\\u8fd0\\u884c agent \\u540e\\u5237\\u65b0\\u3002')\n"
    "        return\n"
    "    cur_tid = st.session_state.selected_trace\n"
    "    sorted_tids = sorted(traces.keys(), key=_trace_start_ns)\n"
    "    for tid in sorted_tids:\n"
    "        row = _fmt_trace_option(tid)\n"
    "        is_cur = (tid == cur_tid)\n"
    "        btn_type = 'primary' if is_cur else 'secondary'\n"
    "        active_cls = ' trace-card-active' if is_cur else ''\n"
    "        st.markdown(\n"
    "            f'<div class=\"trace-card{active_cls}\">',\n"
    "            unsafe_allow_html=True,\n"
    "        )\n"
    "        st.button(\n"
    "            row,\n"
    "            key=f'trace_card_{tid}',\n"
    "            type=btn_type,\n"
    "            use_container_width=True,\n"
    "            on_click=_select_trace,\n"
    "            args=(tid,),\n"
    "        )\n"
    "        st.markdown('</div>', unsafe_allow_html=True)\n"
    "\n"
    "\n"
    "def _render_flowchart_center(sel_spans):\n"
    "    \"\"\"Center column: current trace's span flowchart (TD).\"\"\"\n"
    "    st.markdown('#### \\U0001F500 Agent \\u6d41\\u7a0b\\u56fe')\n"
    "    st.caption(\n"
    "        f'\\u5171 {len(sel_spans)} \\u4e2a span\\u3002'\n"
    "        '\\u70b9\\u51fb\\u8282\\u70b9\\u67e5\\u770b\\u8be6\\u60c5\\uff1b'\n"
    "        '\\u4e0a\\u65b9\\u4e3a\\u8d77\\u59cb\\u65f6\\u95f4\\u6700\\u65e9\\u7684\\u8282\\u70b9\\u3002'\n"
    "    )\n"
    "    _render_mermaid_html(\n"
    "        _build_mermaid(sel_spans, focus=None),\n"
    "        height=720,\n"
    "        key_prefix='explorer',\n"
    "    )\n"
    "\n"
    "\n"
    "def _render_detail_column(sel_spans, all_by_id, focus):\n"
    "    \"\"\"Right column: span detail panel for the focused / selected span.\"\"\"\n"
    "    st.markdown('#### \\U0001F50D Span \\u8be6\\u60c5')\n"
    "    if focus and focus in all_by_id:\n"
    "        if st.button('\\u2190 \\u8fd4\\u56de\\u5168\\u8c8c', key='back_to_overview'):\n"
    "            _clear_focus()\n"
    "        st.session_state.selected_span = focus\n"
    "    elif st.session_state.selected_span and st.session_state.selected_span in all_by_id:\n"
    "        pass\n"
    "    else:\n"
    "        roots = [s for s in sel_spans if not s.get('parent_span_id')]\n"
    "        if roots:\n"
    "            st.session_state.selected_span = roots[0]['span_id']\n"
    "    _render_detail_panel(sel_spans, by_id_all=all_by_id)\n"
    "    if focus and focus not in all_by_id:\n"
    "        _clear_focus()\n"
    "\n"
    "\n"
    "def _jump_to_span(span_id):\n"
    "    \"\"\"Set focus query param (and preserve trace).\"\"\"\n"
    "    st.query_params['focus'] = span_id\n"
    "    st.rerun()\n"
    "\n"
    "\n"
    "def _clear_focus():\n"
    "    \"\"\"Clear focus query param, keep trace.\"\"\"\n"
    "    if 'focus' in st.query_params:\n"
    "        del st.query_params['focus']\n"
    "    st.rerun()\n"
    "\n"
    "\n"
    "def _select_trace(tid):\n"
    "    \"\"\"Switch the active trace; clear any stale focus.\"\"\"\n"
    "    st.session_state.selected_trace = tid\n"
    "    if 'focus' in st.query_params:\n"
    "        del st.query_params['focus']\n"
    "\n"
    "\n"
    "def _trace_start_ns(tid):\n"
    "    \"\"\"Earliest span start_time (ns) in the trace; 0 if empty.\"\"\"\n"
    "    spans = traces.get(tid) or []\n"
    "    if not spans:\n"
    "        return 0\n"
    "    return min(int(s.get('start_time', 0)) for s in spans)\n"
    "\n"
    "\n"
)
content = content.replace(helpers_marker, helpers + helpers_marker, 1)
print("Phase 3: flowchart helpers inserted")

open(p, "w", encoding="utf-8", newline="\n").write(content)