# -*- coding: utf-8 -*-
"""Insert flowchart helpers before # LEFT tree renderer comment block."""
import sys
sys.stdout.reconfigure(encoding="utf-8")
p = r"D:\my-projects\agent-monitor\viewer.py"
with open(p, encoding="utf-8") as f:
    lines = f.read().splitlines(keepends=False)

# Build HELPERS list using actual unicode chars
H = [
    "# ---------------------------------------------------------------------------",
    "# Flowchart mode (Mermaid) + click-to-zoom",
    "# ---------------------------------------------------------------------------",
    "_MERMAID_MAX_NODES = 80",
    "_NODE_LABEL_MAX_CHARS = 60",
    "",
    "",
    "def _mermaid_safe_id(sid):",
    "    return 'n_' + sid.replace('-', '_')",
    "",
    "",
    "def _mermaid_label(span):",
    "    attrs = span.get('attributes') or {}",
    "    kind = span_kind(attrs)",
    "    info = SPAN_KINDS.get(kind, SPAN_KINDS['UNKNOWN'])",
    "    icon = info[0]",
    "    name = _span_display_name(span)",
    "    name = re.sub(r'[\\\"\\\\#;|]', ' ', name).strip()",
    "    if len(name) > _NODE_LABEL_MAX_CHARS:",
    "        name = name[:_NODE_LABEL_MAX_CHARS - 1] + '...'",
    "    start_ns = int(span.get('start_time', 0))",
    "    end_ns = int(span.get('end_time', 0))",
    "    dur_ms = (end_ns - start_ns) / 1_000_000",
    "    dur = _format_duration_ms(dur_ms)",
    "    return f'<b>{icon} {name}</b><br/><small>{kind} &middot; {dur}</small>'",
    "",
    "",
    "def _build_mermaid(spans, *, focus=None, hops=2):",
    "    if not spans:",
    "        return 'flowchart TD\\n    empty[\u3000\uff08\u65e0 span\uff09\u3000]'",
    "    spans_by_id = {s['span_id']: s for s in spans}",
    "    if focus and focus in spans_by_id:",
    "        visible = {focus}",
    "        up, down = {focus}, {focus}",
    "        for _ in range(hops):",
    "            new_up = set()",
    "            for sid in up:",
    "                pid = spans_by_id.get(sid, {}).get('parent_span_id')",
    "                if pid and pid in spans_by_id and pid not in visible:",
    "                    new_up.add(pid)",
    "            visible |= new_up",
    "            up = new_up",
    "            new_down = set()",
    "            for sid in down:",
    "                for s in spans:",
    "                    if s.get('parent_span_id') == sid and s['span_id'] not in visible:",
    "                        new_down.add(s['span_id'])",
    "            visible |= new_down",
    "            down = new_down",
    "    else:",
    "        visible = {s['span_id'] for s in spans}",
    "    visible_spans = [s for s in spans if s['span_id'] in visible]",
    "    if len(visible_spans) > _MERMAID_MAX_NODES and not focus:",
    "        return (",
    "            'flowchart TD\\n'",
    "            '    root[<\u3000\u5171 ' + str(len(spans)) + ' \u4e2a span\u3000<br/>'",
    "            '<small>\u8282\u70b9\u6570\u8fc7\u591a\uff0c\u8bf7\u5207\u56de \u5217\u8868 \u6a21\u5f0f\u67e5\u770b</small>]\\n'",
    "            '    classDef root fill:#4b5563,color:#fff,stroke:#1f2937;\\n'",
    "            '    class root root;')",
    "    visible_spans.sort(key=lambda s: int(s.get('start_time', 0)))",
    "    starts = [int(s.get('start_time', 0)) for s in visible_spans]",
    "    min_start = min(starts) if starts else 0",
    "    out = ['flowchart TD']",
    "    for css in [",
    "        '    classDef llm       fill:#1d4ed8,color:#fff,stroke:#1e3a8a,stroke-width:1px;',",
    "        '    classDef chain     fill:#065f46,color:#fff,stroke:#064e3b,stroke-width:1px;',",
    "        '    classDef tool      fill:#b45309,color:#fff,stroke:#7c2d12,stroke-width:1px;',",
    "        '    classDef agent     fill:#a16207,color:#fff,stroke:#713f12,stroke-width:1px;',",
    "        '    classDef retriever fill:#7e22ce,color:#fff,stroke:#581c87,stroke-width:1px;',",
    "        '    classDef embedding fill:#0e7490,color:#fff,stroke:#164e63,stroke-width:1px;',",
    "        '    classDef reranker  fill:#6d28d9,color:#fff,stroke:#4c1d95,stroke-width:1px;',",
    "        '    classDef prompt    fill:#3f6212,color:#fff,stroke:#365314,stroke-width:1px;',",
    "        '    classDef parser    fill:#4b5563,color:#fff,stroke:#1f2937,stroke-width:1px;',",
    "        '    classDef evaluator fill:#a8a29e,color:#1c1917,stroke:#78716c,stroke-width:1px;',",
    "        '    classDef guardrail fill:#b91c1c,color:#fff,stroke:#7f1d1d,stroke-width:1px;',",
    "        '    classDef unknown   fill:#6b7280,color:#fff,stroke:#374151,stroke-width:1px;',",
    "        '    classDef error     stroke:#ef4444,stroke-width:2px,color:#fff;',",
    "        '    classDef focus     stroke:#facc15,stroke-width:3px;',",
    "        '    linkStyle default stroke:#64748b,stroke-width:1px;']:",
    "        out.append(css)",
    "    children_by_parent = {}",
    "    for s in visible_spans:",
    "        pid = s.get('parent_span_id')",
    "        if pid and pid in visible:",
    "            children_by_parent.setdefault(pid, []).append(s)",
    "    _handled_parents = set()",
    "    for span in visible_spans:",
    "        sid = span['span_id']",
    "        nid = _mermaid_safe_id(sid)",
    "        kind = span_kind(span.get('attributes') or {})",
    "        kind_class = kind.lower() if kind in SPAN_KINDS else 'unknown'",
    "        cls = [kind_class]",
    "        if str(span.get('status', '')).upper() == 'ERROR':",
    "            cls.append('error')",
    "        if sid == focus:",
    "            cls.append('focus')",
    "        start_ns = int(span.get('start_time', 0))",
    "        offset_ms = int((start_ns - min_start) / 1_000_000)",
    "        label = _mermaid_label(span)",
    "        full_label = f\"{label}<br/><small>t+{offset_ms}ms</small>\"",
    "        safe = re.sub(r'[\\\"\\\\#;|]', ' ', full_label).strip()",
    "        out.append(f'    {nid}[\"{safe}\"]')",
    "        out.append(f'    class {nid} {\",\".join(cls)};')",
    "    for parent_id, kids in children_by_parent.items():",
    "        if len(kids) < 2:",
    "            continue",
    "        sorted_kids = sorted(kids, key=lambda s: int(s.get('start_time', 0)))",
    "        n_kids = len(sorted_kids)",
    "        all_sequential = True",
    "        for i in range(n_kids - 1):",
    "            prev_end = int(sorted_kids[i].get('end_time', 0))",
    "            next_start = int(sorted_kids[i + 1].get('start_time', 0))",
    "            if next_start < prev_end:",
    "                all_sequential = False",
    "                break",
    "        pnid = _mermaid_safe_id(parent_id)",
    "        if all_sequential:",
    "            _handled_parents.add(parent_id)",
    "            first_id = _mermaid_safe_id(sorted_kids[0]['span_id'])",
    "            out.append(f'    {pnid} --> {first_id}')",
    "            for i in range(n_kids - 1):",
    "                a = _mermaid_safe_id(sorted_kids[i]['span_id'])",
    "                b = _mermaid_safe_id(sorted_kids[i + 1]['span_id'])",
    "                out.append(f'    {a} --> {b}')",
    "        else:",
    "            _handled_parents.add(parent_id)",
    "            out.append('    subgraph SG_' + pnid + '[\"\u5e76\u884c\u5206\u652f\"]')",
    "            out.append('    direction LR')",
    "            for k in sorted_kids:",
    "                out.append('        ' + _mermaid_safe_id(k['span_id']))",
    "            out.append('    end')",
    "            for k in sorted_kids:",
    "                out.append(f'    {pnid} --> {_mermaid_safe_id(k[\"span_id\"])}')",
    "    for span in visible_spans:",
    "        pid = span.get('parent_span_id')",
    "        if pid and pid in visible and pid not in _handled_parents:",
    "            out.append(f'    {_mermaid_safe_id(pid)} --> {_mermaid_safe_id(span[\"span_id\"])}')",
    "    for span in visible_spans:",
    "        nid = _mermaid_safe_id(span['span_id'])",
    "        out.append(f'    click {nid} focusSpan')",
    "    return '\\n'.join(out)",
    "",
    "",
    "def _render_mermaid_html(src, *, height=620, key_prefix='m'):",
    "    js_src = src.replace('\\\\', '\\\\\\\\').replace('`', '\\\\`').replace('${', '\\\\${')",
    "    html_doc = (",
    "        '<!DOCTYPE html>\\n<html><head><meta charset=\"utf-8\">\\n<style>\\n'",
    "        'body{margin:0;padding:8px;background:transparent;color:#e5e7eb;font-family:ui-system,system-ui,sans-serif;}\\n'",
    "        '.mermaid{background:rgba(255,255,255,0.02);border-radius:8px;padding:8px;overflow-x:auto;}\\n'",
    "        '.node{cursor:pointer;}\\n'",
    "        '.node:hover rect,.node:hover polygon{filter:brightness(1.25);}\\n'",
    "        '</style>\\n'",
    "        '<script src=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js\"></script>\\n'",
    "        '</head><body>\\n'",
    "        '<div class=\"mermaid\" id=\"m_' + key_prefix + '\">\\n'",
    "        + js_src + '\\n'",
    "        '</div>\\n<script>\\n'",
    "        'window.focusSpan=function(nodeId){'",
    "        'var spanId=(nodeId||\"\").replace(/^n_/,\"\").replace(/_/g,\"-\");'",
    "        'if(!spanId)return;'",
    "        'var url=new URL(window.top.location.href);'",
    "        'url.searchParams.set(\"focus\",spanId);'",
    "        'try{window.top.location.href=url.toString();}'",
    "        'catch(e1){try{window.parent.location.href=url.toString();}catch(e2){window.location.href=url.toString();}}'",
    "        '};'",
    "        'mermaid.initialize({startOnLoad:true,theme:\"dark\",'",
    "        'themeVariables:{background:\"#0f172a\",primaryColor:\"#1e293b\",'",
    "        'primaryTextColor:\"#e5e7eb\",primaryBorderColor:\"#334155\",'",
    "        'lineColor:\"#64748b\",fontFamily:\"ui-system,system-ui,sans-serif\"},'",
    "        'flowchart:{curve:\"basis\",htmlLabels:true,useMaxWidth:true},'",
    "        'securityLevel:\"loose\"})'",
    "        '.then(function(){document.querySelectorAll(\".mermaid .node\").forEach(function(node){node.addEventListener(\"click\",function(){var id=node.id||(node.querySelector(\"[id]\")?node.querySelector(\"[id]\").id:\"\");var m=id.match(/n_[A-Za-z0-9_]+/);if(m)window.focusSpan(m[0]);});});});'",
    "        '</script>\\n</body></html>')",
    "    st.components.v1.html(html_doc, height=height, scrolling=True)",
    "",
    "",
    "def _render_flowchart_mode(sel_spans, kpi, all_by_id):",
    "    _url_trace = st.query_params.get('trace')",
    "    if _url_trace and _url_trace in traces:",
    "        if st.session_state.selected_trace != _url_trace:",
    "            st.session_state.selected_trace = _url_trace",
    "            sel_spans = traces[_url_trace]",
    "            all_by_id = {s['span_id']: s for s in sel_spans}",
    "            kpi = _aggregate_kpi(sel_spans)",
    "    focus = st.query_params.get('focus')",
    "    col_left, col_center, col_right = st.columns([1.1, 2.5, 1.3])",
    "    with col_left:",
    "        _render_trace_cards_list()",
    "    with col_center:",
    "        _render_flowchart_center(sel_spans)",
    "    with col_right:",
    "        _render_detail_column(sel_spans, all_by_id, focus)",
    "",
    "",
    "def _render_trace_cards_list():",
    "    st.markdown('#### \U0001F4CB Traces')",
    "    if not traces:",
    "        st.caption('\u8fd8\u6ca1\u6709 trace\u3002\u8bf7\u8fd0\u884c agent \u540e\u5237\u65b0\u3002')",
    "        return",
    "    cur_tid = st.session_state.selected_trace",
    "    sorted_tids = sorted(traces.keys(), key=_trace_start_ns)",
    "    for tid in sorted_tids:",
    "        row = _fmt_trace_option(tid)",
    "        is_cur = (tid == cur_tid)",
    "        btn_type = 'primary' if is_cur else 'secondary'",
    "        active_cls = ' trace-card-active' if is_cur else ''",
    "        st.markdown(f'<div class=\"trace-card{active_cls}\">', unsafe_allow_html=True)",
    "        st.button(",
    "            row,",
    "            key=f'trace_card_{tid}',",
    "            type=btn_type,",
    "            use_container_width=True,",
    "            on_click=_select_trace,",
    "            args=(tid,),",
    "        )",
    "        st.markdown('</div>', unsafe_allow_html=True)",
    "",
    "",
    "def _render_flowchart_center(sel_spans):",
    "    st.markdown('#### \U0001F500 Agent \u6d41\u7a0b\u56fe')",
    "    st.caption(",
    "        f'\u5171 {len(sel_spans)} \u4e2a span\u3002'",
    "        '\u70b9\u51fb\u8282\u70b9\u67e5\u770b\u8be6\u60c5\uff1b'",
    "        '\u4e0a\u65b9\u4e3a\u8d77\u59cb\u65f6\u95f4\u6700\u65e9\u7684\u8282\u70b9\u3002'",
    "    )",
    "    _render_mermaid_html(_build_mermaid(sel_spans, focus=None), height=720, key_prefix='explorer')",
    "",
    "",
    "def _render_detail_column(sel_spans, all_by_id, focus):",
    "    st.markdown('#### \U0001F50D Span \u8be6\u60c5')",
    "    if focus and focus in all_by_id:",
    "        if st.button('\u2190 \u8fd4\u56de\u5168\u8c8c', key='back_to_overview'):",
    "            _clear_focus()",
    "        st.session_state.selected_span = focus",
    "    elif st.session_state.selected_span and st.session_state.selected_span in all_by_id:",
    "        pass",
    "    else:",
    "        roots = [s for s in sel_spans if not s.get('parent_span_id')]",
    "        if roots:",
    "            st.session_state.selected_span = roots[0]['span_id']",
    "    _render_detail_panel(sel_spans, by_id_all=all_by_id)",
    "    if focus and focus not in all_by_id:",
    "        _clear_focus()",
    "",
    "",
    "def _jump_to_span(span_id):",
    "    st.query_params['focus'] = span_id",
    "    st.rerun()",
    "",
    "",
    "def _clear_focus():",
    "    if 'focus' in st.query_params:",
    "        del st.query_params['focus']",
    "    st.rerun()",
    "",
    "",
    "def _select_trace(tid):",
    "    st.session_state.selected_trace = tid",
    "    if 'focus' in st.query_params:",
    "        del st.query_params['focus']",
    "",
    "",
    "def _trace_start_ns(tid):",
    "    spans = traces.get(tid) or []",
    "    if not spans:",
    "        return 0",
    "    return min(int(s.get('start_time', 0)) for s in spans)",
    "",
    "",
]

# Insert before "LEFT tree renderer" line (which is preceded by # === and the comment is at 0-idx = L1066 - 1 = 1065)
# Actually find exact position
left_tree_idx = None
for i, l in enumerate(lines):
    if "LEFT tree renderer" in l:
        left_tree_idx = i
        break
# Insert before the # === line above
anchor = left_tree_idx - 1
print(f"Inserting helpers at 0-idx {anchor}")
lines[anchor:anchor] = H

with open(p, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print("Helpers done:", len(lines), "lines")
