# -*- coding: utf-8 -*-
"""Phase 3-6: helpers, radio, body wrap, IO side-by-side."""
import sys
sys.stdout.reconfigure(encoding="utf-8")

p = r"D:\my-projects\agent-monitor\viewer.py"
content = open(p, encoding="utf-8").read()

# ----- Phase 3: helpers -----
helpers_marker = "# LEFT tree renderer"
assert helpers_marker in content

helpers = (
    "# ---------------------------------------------------------------------------\n"
    "# Flowchart mode (Mermaid) + click-to-zoom\n"
    "# ---------------------------------------------------------------------------\n"
    "_MERMAID_MAX_NODES = 80\n"
    "_NODE_LABEL_MAX_CHARS = 60\n"
    "\n"
    "\n"
    "def _mermaid_safe_id(sid):\n"
    "    return 'n_' + sid.replace('-', '_')\n"
    "\n"
    "\n"
    "def _mermaid_label(span):\n"
    "    attrs = span.get('attributes') or {}\n"
    "    kind = span_kind(attrs)\n"
    "    info = SPAN_KINDS.get(kind, SPAN_KINDS['UNKNOWN'])\n"
    "    icon = info[0]\n"
    "    name = _span_display_name(span)\n"
    "    name = re.sub(r'[\\[\\](){}<>|`]', ' ', name).strip()\n"
    "    if len(name) > _NODE_LABEL_MAX_CHARS:\n"
    "        name = name[:_NODE_LABEL_MAX_CHARS - 1] + '...'\n"
    "    start_ns = int(span.get('start_time', 0))\n"
    "    end_ns = int(span.get('end_time', 0))\n"
    "    dur_ms = (end_ns - start_ns) / 1_000_000\n"
    "    dur = _format_duration_ms(dur_ms)\n"
    "    return f'<b>{icon} {name}</b><br/><small>{kind} &middot; {dur}</small>'\n"
    "\n"
    "\n"
    "def _build_mermaid(spans, *, focus=None, hops=2):\n"
    "    if not spans:\n"
    "        return 'flowchart TB\\n    empty[\\u3000\\uff08\\u65e0 span\\uff09\\u3000]'\n"
    "    spans_by_id = {s['span_id']: s for s in spans}\n"
    "    if focus and focus in spans_by_id:\n"
    "        visible = {focus}\n"
    "        up, down = {focus}, {focus}\n"
    "        for _ in range(hops):\n"
    "            new_up = set()\n"
    "            for sid in up:\n"
    "                pid = spans_by_id.get(sid, {}).get('parent_span_id')\n"
    "                if pid and pid in spans_by_id and pid not in visible:\n"
    "                    new_up.add(pid)\n"
    "            visible |= new_up\n"
    "            up = new_up\n"
    "            new_down = set()\n"
    "            for sid in down:\n"
    "                for s in spans:\n"
    "                    if s.get('parent_span_id') == sid and s['span_id'] not in visible:\n"
    "                        new_down.add(s['span_id'])\n"
    "            visible |= new_down\n"
    "            down = new_down\n"
    "    else:\n"
    "        visible = {s['span_id'] for s in spans}\n"
    "    visible_spans = [s for s in spans if s['span_id'] in visible]\n"
    "    if len(visible_spans) > _MERMAID_MAX_NODES and not focus:\n"
    "        return (\n"
    "            'flowchart TB\\n'\n"
    "            '    root[<\\u3000\\u5171 ' + str(len(spans)) + ' \\u4e2a span\\u3000<br/>'\n"
    "            \"<small>\\u8282\\u70b9\\u6570\\u8fc7\\u591a\\uff0c\\u8bf7\\u5207\\u56de \\u5217\\u8868 \\u6a21\\u5f0f\\u67e5\\u770b</small>]\\n\"\n"
    "            '    classDef root fill:#4b5563,color:#fff,stroke:#1f2937;\\n'\n"
    "            '    class root root;'\n"
    "        )\n"
    "    out = ['flowchart TB']\n"
    "    out.append('    classDef llm       fill:#1d4ed8,color:#fff,stroke:#1e3a8a,stroke-width:1px;')\n"
    "    out.append('    classDef chain     fill:#065f46,color:#fff,stroke:#064e3b,stroke-width:1px;')\n"
    "    out.append('    classDef tool      fill:#b45309,color:#fff,stroke:#7c2d12,stroke-width:1px;')\n"
    "    out.append('    classDef agent     fill:#a16207,color:#fff,stroke:#713f12,stroke-width:1px;')\n"
    "    out.append('    classDef retriever fill:#7e22ce,color:#fff,stroke:#581c87,stroke-width:1px;')\n"
    "    out.append('    classDef embedding fill:#0e7490,color:#fff,stroke:#164e63,stroke-width:1px;')\n"
    "    out.append('    classDef reranker  fill:#6d28d9,color:#fff,stroke:#4c1d95,stroke-width:1px;')\n"
    "    out.append('    classDef prompt    fill:#3f6212,color:#fff,stroke:#365314,stroke-width:1px;')\n"
    "    out.append('    classDef parser    fill:#4b5563,color:#fff,stroke:#1f2937,stroke-width:1px;')\n"
    "    out.append('    classDef evaluator fill:#a8a29e,color:#1c1917,stroke:#78716c,stroke-width:1px;')\n"
    "    out.append('    classDef guardrail fill:#b91c1c,color:#fff,stroke:#7f1d1d,stroke-width:1px;')\n"
    "    out.append('    classDef unknown   fill:#6b7280,color:#fff,stroke:#374151,stroke-width:1px;')\n"
    "    out.append('    classDef error     stroke:#ef4444,stroke-width:2px,color:#fff;')\n"
    "    out.append('    classDef focus     stroke:#facc15,stroke-width:3px;')\n"
    "    out.append('    linkStyle default stroke:#64748b,stroke-width:1px;')\n"
    "    for span in visible_spans:\n"
    "        sid = span['span_id']\n"
    "        nid = _mermaid_safe_id(sid)\n"
    "        kind = span_kind(span.get('attributes') or {})\n"
    "        kind_class = kind.lower() if kind in SPAN_KINDS else 'unknown'\n"
    "        cls = [kind_class]\n"
    "        if str(span.get('status', '')).upper() == 'ERROR':\n"
    "            cls.append('error')\n"
    "        if sid == focus:\n"
    "            cls.append('focus')\n"
    "        out.append(f'    {nid}[\"{_mermaid_label(span)}\"]')\n"
    "        out.append(f'    class {nid} {\",\".join(cls)};')\n"
    "    for span in visible_spans:\n"
    "        pid = span.get('parent_span_id')\n"
    "        if pid and pid in visible:\n"
    "            out.append(f'    {_mermaid_safe_id(pid)} --> {_mermaid_safe_id(span[\"span_id\"])}')\n"
    "    return '\\n'.join(out)\n"
    "\n"
    "\n"
    "def _render_mermaid_html(src, *, height=620, key_prefix='m'):\n"
    "    js_src = (\n"
    "        src.replace('\\\\', '\\\\\\\\')\n"
    "           .replace('`', '\\\\`')\n"
    "           .replace('${', '\\\\${')\n"
    "    )\n"
    "    html_doc = (\n"
    "        '<!DOCTYPE html>\\n'\n"
    "        '<html><head><meta charset=\"utf-8\">\\n'\n"
    "        '<style>\\n'\n"
    "        '  body { margin: 0; padding: 8px; background: transparent;\\n'\n"
    "        \"         color: #e5e7eb; font-family: ui-system, system-ui, sans-serif; }\\n\"\n"
    "        '  .mermaid { background: rgba(255,255,255,0.02); border-radius: 8px; padding: 8px; }\\n'\n"
    "        '  .node { cursor: pointer; }\\n'\n"
    "        '  .node:hover rect, .node:hover polygon { filter: brightness(1.25); }\\n'\n"
    "        '</style>\\n'\n"
    "        '<script src=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js\"></script>\\n'\n"
    "        '</head><body>\\n'\n"
    "        \"<div class='mermaid' id='m_\" + key_prefix + \"'>\\n\"\n"
    "        + js_src + '\\n'\n"
    "        \"</div>\\n\"\n"
    "        \"<script>\\n\"\n"
    "        \"  mermaid.initialize({\\n\"\n"
    "        \"    startOnLoad: true,\\n\"\n"
    "        \"    theme: 'dark',\\n\"\n"
    "        \"    themeVariables: {\\n\"\n"
    "        \"      background: '#0f172a',\\n\"\n"
    "        \"      primaryColor: '#1e293b',\\n\"\n"
    "        \"      primaryTextColor: '#e5e7eb',\\n\"\n"
    "        \"      primaryBorderColor: '#334155',\\n\"\n"
    "        \"      lineColor: '#64748b',\\n\"\n"
    "        \"      fontFamily: 'ui-system, system-ui, sans-serif',\\n\"\n"
    "        \"    },\\n\"\n"
    "        \"    flowchart: { curve: 'basis', htmlLabels: true, useMaxWidth: true },\\n\"\n"
    "        \"    securityLevel: 'loose',\\n\"\n"
    "        \"  }).then(() => {\\n\"\n"
    "        \"    document.querySelectorAll('.mermaid .node').forEach(node => {\\n\"\n"
    "        \"      node.addEventListener('click', () => {\\n\"\n"
    "        \"        const id = node.id || (node.querySelector('[id]') ? node.querySelector('[id]').id : '');\\n\"\n"
    "        \"        const m = id.match(/n_[A-Za-z0-9_]+/);\\n\"\n"
    "        \"        if (!m) return;\\n\"\n"
    "        \"        const spanId = m[0].substring(2).replace(/_/g, '-');\\n\"\n"
    "        \"        const url = new URL(window.parent.location.href);\\n\"\n"
    "        \"        url.searchParams.set('focus', spanId);\\n\"\n"
    "        \"        window.parent.location.href = url.toString();\\n\"\n"
    "        \"      });\\n\"\n"
    "        \"    });\\n\"\n"
    "        \"  });\\n\"\n"
    "        \"</script>\\n\"\n"
    "        \"</body></html>\"\n"
    "    )\n"
    "    st.components.v1.html(html_doc, height=height, scrolling=True)\n"
    "\n"
    "\n"
    "def _render_flowchart_mode(sel_spans, kpi, all_by_id):\n"
    "    focus = st.query_params.get('focus')\n"
    "    if focus and focus in all_by_id:\n"
    "        focused_span = all_by_id[focus]\n"
    "        st.markdown(\n"
    "            f\"#### \\U0001F50D \\u805a\\u7126\\u3000\\u00b7\\u3000{_span_display_name(focused_span)}\"\n"
    "        )\n"
    "        if st.button('\\u2190 \\u8fd4\\u56de\\u5168\\u8c8c', key='back_to_overview'):\n"
    "            if 'focus' in st.query_params:\n"
    "                del st.query_params['focus']\n"
    "            st.rerun()\n"
    "        st.caption(\n"
    "            '\\u663e\\u793a\\u9009\\u4e2d\\u8282\\u70b9\\u53ca\\u5176 2 \\u8df3\\u90bb\\u57df\\u3002'\n"
    "            '\\u70b9\\u51fb\\u300c\\u8fd4\\u56de\\u5168\\u8c8c\\u300d\\u6216\\u6e05\\u9664 URL \\u4e2d\\u7684 focus \\u53c2\\u6570\\u53ef\\u9000\\u51fa\\u3002'\n"
    "        )\n"
    "        fcol_l, fcol_r = st.columns([1.3, 1])\n"
    "        with fcol_l:\n"
    "            st.markdown('##### \\u8fd1\\u90e8\\u5b50\\u56fe')\n"
    "            _render_mermaid_html(\n"
    "                _build_mermaid(sel_spans, focus=focus, hops=2),\n"
    "                height=620, key_prefix='focus',\n"
    "            )\n"
    "        with fcol_r:\n"
    "            st.markdown('##### \\u8be6\\u60c5\\u9762\\u677f')\n"
    "            st.session_state.selected_span = focus\n"
    "            _render_detail_panel(sel_spans, by_id_all=all_by_id)\n"
    "    else:\n"
    "        st.markdown('#### \\U0001F500 Agent \\u6d41\\u7a0b\\u56fe')\n"
    "        st.caption(\n"
    "            f'\\u5171 {len(sel_spans)} \\u4e2a span\\u3002'\n"
    "            '\\u70b9\\u51fb\\u8282\\u70b9\\u53ef\\u653e\\u5927\\u67e5\\u770b\\u8be6\\u60c5\\uff1b'\n"
    "            '\\u5207\\u56de\\u300c\\u5217\\u8868\\u300d\\u6a21\\u5f0f\\u67e5\\u770b\\u5b8c\\u6574\\u6811\\u3002'\n"
    "        )\n"
    "        _render_mermaid_html(\n"
    "            _build_mermaid(sel_spans, focus=None),\n"
    "            height=720, key_prefix='full',\n"
    "        )\n"
    "        if focus and focus not in all_by_id:\n"
    "            if 'focus' in st.query_params:\n"
    "                del st.query_params['focus']\n"
    "            st.rerun()\n"
    "\n"
    "\n"
)
content = content.replace(helpers_marker, helpers + helpers_marker, 1)
print("Phase 3: helpers inserted")

# ----- Phase 4: radio -----
anchor = "# Build filtered span list + tree structure"
assert anchor in content
radio = (
    "\n# ---------------------------------------------------------------------------\n"
    "# View-mode switcher\n"
    "# ---------------------------------------------------------------------------\n"
    "st.session_state.setdefault('view_mode', '\u5217\u8868')\n"
    "_view_opts = ['\u5217\u8868', '\u6d41\u7a0b\u56fe']\n"
    "_view_idx = _view_opts.index(st.session_state.view_mode) if st.session_state.view_mode in _view_opts else 0\n"
    "st.radio(\n"
    "    '\u89c6\u56fe\u6a21\u5f0f',\n"
    "    options=_view_opts,\n"
    "    index=_view_idx,\n"
    "    horizontal=True,\n"
    "    key='view_mode',\n"
    "    label_visibility='collapsed',\n"
    ")\n\n"
)
content = content.replace(anchor, radio + anchor, 1)
print("Phase 4: radio inserted")

# ----- Phase 5: body wrap -----
body_start = content.find("col_tree, col_detail, col_meta = st.columns")
body_end_marker = '_render_metadata_panel(kpi, sel_spans, by_id_all={s["span_id"]: s for s in sel_spans})\n'
end_idx = content.find(body_end_marker, body_start) + len(body_end_marker)
assert body_start > 0 and end_idx > body_start, f"body: {body_start}..{end_idx}"

new_body = (
    "if st.session_state.view_mode == '\u5217\u8868':\n"
    "    col_tree, col_detail, col_meta = st.columns([1.1, 2.6, 1.3])\n"
    "\n"
    "    # =======================================================================\n"
    "    # LEFT column - navigation tree\n"
    "    # =======================================================================\n"
    "    with col_tree:\n"
    "        st.markdown(\n"
    "            f'#### \U0001F5C2 \u5bfc\u822a\u6811 '\n"
    "            f'<span style=\"color:#9ca3af;font-size:11px;font-weight:400\">'\n"
    "            f'\u00b7 {len(filtered_spans)} spans</span>',\n"
    "            unsafe_allow_html=True,\n"
    "        )\n"
    "\n"
    "        def _select_only(sid):\n"
    "            st.session_state.selected_span = sid\n"
    "\n"
    "        def _toggle_expand(sid):\n"
    "            if sid in st.session_state.expanded_spans:\n"
    "                st.session_state.expanded_spans.discard(sid)\n"
    "            else:\n"
    "                st.session_state.expanded_spans.add(sid)\n"
    "\n"
    "        _render_tree(roots, children_map, depth=0)\n"
    "\n"
    "    # =======================================================================\n"
    "    # CENTER column - detail panel\n"
    "    # =======================================================================\n"
    "    with col_detail:\n"
    "        st.markdown('#### \U0001F50D Span \u8be6\u60c5')\n"
    "        _render_detail_panel(sel_spans, by_id_all={s['span_id']: s for s in sel_spans})\n"
    "\n"
    "    # =======================================================================\n"
    "    # RIGHT column - metadata indicator panel\n"
    "    # =======================================================================\n"
    "    with col_meta:\n"
    "        st.markdown('#### \U0001F4CA \u5143\u6570\u636e\u9762\u677f')\n"
    "        _render_metadata_panel(kpi, sel_spans, by_id_all={s['span_id']: s for s in sel_spans})\n"
    "\n"
    "else:  # \u6d41\u7a0b\u56fe mode\n"
    "    _render_flowchart_mode(\n"
    "        sel_spans,\n"
    "        kpi,\n"
    "        all_by_id={s['span_id']: s for s in sel_spans},\n"
    "    )\n"
)
content = content[:body_start] + new_body + content[end_idx:]
print("Phase 5: body wrapped")

# ----- Phase 6: IO side-by-side -----
io_start = content.find("# --- Input block (collapsible)")
io_end = content.find("# --- Token breakdown")
assert io_start > 0 and io_end > io_start, f"io: {io_start}..{io_end}"

new_io = (
    "    # --- Input / Output side-by-side (headers aligned; each side scrolls independently) --\n"
    "    c_in, c_out = st.columns(2, gap='medium')\n"
    "\n"
    "    with c_in:\n"
    "        st.markdown('<div class=\"io-col-head in-head\">\u2b07  \u8f93\u5165</div>', unsafe_allow_html=True)\n"
    "        if kind == 'LLM':\n"
    "            msgs = to_messages(canon(attrs, 'messages.input'))\n"
    "            if msgs:\n"
    "                for m in msgs:\n"
    "                    role = (m.get('role') or 'user').lower()\n"
    "                    content_val = m.get('content') or ''\n"
    "                    _render_msg(role, content_val)\n"
    "                    for tc in m.get('tool_calls') or []:\n"
    "                        nm = tc.get('name') or 'tool'\n"
    "                        with st.expander(f'\U0001F527 {nm}'):\n"
    "                            st.json(tc.get('arguments'))\n"
    "            else:\n"
    "                _render_input_fallback(attrs, 'input.value')\n"
    "        elif kind == 'TOOL':\n"
    "            tp = canon(attrs, 'tool.parameters')\n"
    "            st.markdown('**\u5de5\u5177\u53c2\u6570\uff1a**')\n"
    "            if tp is None:\n"
    "                st.caption('\uff08\u672a\u6355\u83b7\u53c2\u6570\uff09')\n"
    "            elif isinstance(tp, str):\n"
    "                try:\n"
    "                    st.json(json.loads(tp))\n"
    "                except (json.JSONDecodeError, TypeError):\n"
    "                    st.code(tp)\n"
    "            else:\n"
    "                st.json(tp)\n"
    "        else:\n"
    "            _render_input_fallback(attrs, 'input.value')\n"
    "\n"
    "    with c_out:\n"
    "        st.markdown('<div class=\"io-col-head out-head\">\u2b06  \u8f93\u51fa</div>', unsafe_allow_html=True)\n"
    "        if kind == 'LLM':\n"
    "            msgs = to_messages(canon(attrs, 'messages.output'))\n"
    "            if msgs:\n"
    "                for m in msgs:\n"
    "                    role = (m.get('role') or 'assistant').lower()\n"
    "                    content_val = m.get('content') or ''\n"
    "                    _render_msg(role, content_val)\n"
    "            else:\n"
    "                _render_input_fallback(attrs, 'output.value')\n"
    "        elif kind == 'TOOL':\n"
    "            tout = canon(attrs, 'tool.output')\n"
    "            if tout is None:\n"
    "                st.caption('\uff08\u672a\u6355\u83b7\u8fd4\u56de\u7ed3\u679c\uff09')\n"
    "            elif isinstance(tout, (dict, list)):\n"
    "                st.json(tout)\n"
    "            elif isinstance(tout, str):\n"
    "                try:\n"
    "                    parsed = json.loads(tout)\n"
    "                    if isinstance(parsed, (dict, list)):\n"
    "                        st.json(parsed)\n"
    "                    else:\n"
    "                        st.code(str(parsed))\n"
    "                except (json.JSONDecodeError, TypeError):\n"
    "                    if len(tout) > 6000:\n"
    "                        st.code(tout[:6000] + '\\n\\u2026(truncated)')\n"
    "                    else:\n"
    "                        st.code(tout)\n"
    "            else:\n"
    "                st.code(str(tout))\n"
    "        else:\n"
    "            _render_input_fallback(attrs, 'output.value')\n"
    "\n"
)
content = content[:io_start] + new_io + content[io_end:]
print("Phase 6: IO side-by-side")

open(p, "w", encoding="utf-8", newline="\n").write(content)
print("Bytes written:", len(content.encode("utf-8")))