# -*- coding: utf-8 -*-
"""Refactor _render_run_tab to side-by-side Input/Output."""
import sys
sys.stdout.reconfigure(encoding="utf-8")

p = r"D:\my-projects\agent-monitor\viewer.py"
src = open(p, encoding="utf-8").read()

# Old block: the two sequential expanders
old = (
    '    # --- Input block (collapsible) ------------------------------------------\n'
    '    input_open = True\n'
    '    with st.expander("\u2b07  \u8f93\u5165", expanded=input_open):\n'
    '        if kind == "LLM":\n'
    '            msgs = to_messages(canon(attrs, "messages.input"))\n'
    '            if msgs:\n'
    '                for m in msgs:\n'
    '                    role = (m.get("role") or "user").lower()\n'
    '                    content = m.get("content") or ""\n'
    '                    _render_msg(role, content)\n'
    '                    for tc in m.get("tool_calls") or []:\n'
    '                        nm = tc.get("name") or "tool"\n'
    '                        with st.expander(f"\U0001F527 {nm}"):\n'
    '                            st.json(tc.get("arguments"))\n'
    '            else:\n'
    '                _render_input_fallback(attrs, "input.value")\n'
    '        elif kind == "TOOL":\n'
    '            tp = canon(attrs, "tool.parameters")\n'
    '            st.markdown("**\u5de5\u5177\u53c2\u6570\uff1a**")\n'
    '            if tp is None:\n'
    '                st.caption("\uff08\u672a\u6355\u83b7\u53c2\u6570\uff09")\n'
    '            elif isinstance(tp, str):\n'
    '                try:\n'
    '                    st.json(json.loads(tp))\n'
    '                except (json.JSONDecodeError, TypeError):\n'
    '                    st.code(tp)\n'
    '            else:\n'
    '                st.json(tp)\n'
    '        else:\n'
    '            _render_input_fallback(attrs, "input.value")\n'
    '\n'
    '    # --- Output block (collapsible) -----------------------------------------\n'
    '    with st.expander("\u2b06  \u8f93\u51fa", expanded=True):\n'
    '        if kind == "LLM":\n'
    '            msgs = to_messages(canon(attrs, "messages.output"))\n'
    '            if msgs:\n'
    '                for m in msgs:\n'
    '                    role = (m.get("role") or "assistant").lower()\n'
    '                    content = m.get("content") or ""\n'
    '                    _render_msg(role, content)\n'
    '            else:\n'
    '                _render_input_fallback(attrs, "output.value")\n'
    '        elif kind == "TOOL":\n'
    '            tout = canon(attrs, "tool.output")\n'
    '            if tout is None:\n'
    '                st.caption("\uff08\u672a\u6355\u83b7\u8fd4\u56de\u7ed3\u679c\uff09")\n'
    '            elif isinstance(tout, (dict, list)):\n'
    '                st.json(tout)\n'
    '            elif isinstance(tout, str):\n'
    '                try:\n'
    '                    parsed = json.loads(tout)\n'
    '                    if isinstance(parsed, (dict, list)):\n'
    '                        st.json(parsed)\n'
    '                    else:\n'
    '                        st.code(str(parsed))\n'
    '                except (json.JSONDecodeError, TypeError):\n'
    '                    if len(tout) > 6000:\n'
    '                        st.code(tout[:6000] + "\n\u2026(truncated)")\n'
    '                    else:\n'
    '                        st.code(tout)\n'
    '            else:\n'
    '                st.code(str(tout))\n'
    '        else:\n'
    '            _render_input_fallback(attrs, "output.value")\n'
)

assert old in src, "Input/Output old block not found"

new = (
    '    # --- Input / Output side-by-side (headers aligned, each side scrolls independently) --\n'
    '    c_in, c_out = st.columns(2, gap="medium")\n'
    '\n'
    '    with c_in:\n'
    '        st.markdown(\'<div class="io-col-head in-head">\u2b07  \u8f93\u5165</div>\', unsafe_allow_html=True)\n'
    '        if kind == "LLM":\n'
    '            msgs = to_messages(canon(attrs, "messages.input"))\n'
    '            if msgs:\n'
    '                for m in msgs:\n'
    '                    role = (m.get("role") or "user").lower()\n'
    '                    content = m.get("content") or ""\n'
    '                    _render_msg(role, content)\n'
    '                    for tc in m.get("tool_calls") or []:\n'
    '                        nm = tc.get("name") or "tool"\n'
    '                        with st.expander(f"\U0001F527 {nm}"):\n'
    '                            st.json(tc.get("arguments"))\n'
    '            else:\n'
    '                _render_input_fallback(attrs, "input.value")\n'
    '        elif kind == "TOOL":\n'
    '            tp = canon(attrs, "tool.parameters")\n'
    '            st.markdown("**\u5de5\u5177\u53c2\u6570\uff1a**")\n'
    '            if tp is None:\n'
    '                st.caption("\uff08\u672a\u6355\u83b7\u53c2\u6570\uff09")\n'
    '            elif isinstance(tp, str):\n'
    '                try:\n'
    '                    st.json(json.loads(tp))\n'
    '                except (json.JSONDecodeError, TypeError):\n'
    '                    st.code(tp)\n'
    '            else:\n'
    '                st.json(tp)\n'
    '        else:\n'
    '            _render_input_fallback(attrs, "input.value")\n'
    '\n'
    '    with c_out:\n'
    '        st.markdown(\'<div class="io-col-head out-head">\u2b06  \u8f93\u51fa</div>\', unsafe_allow_html=True)\n'
    '        if kind == "LLM":\n'
    '            msgs = to_messages(canon(attrs, "messages.output"))\n'
    '            if msgs:\n'
    '                for m in msgs:\n'
    '                    role = (m.get("role") or "assistant").lower()\n'
    '                    content = m.get("content") or ""\n'
    '                    _render_msg(role, content)\n'
    '            else:\n'
    '                _render_input_fallback(attrs, "output.value")\n'
    '        elif kind == "TOOL":\n'
    '            tout = canon(attrs, "tool.output")\n'
    '            if tout is None:\n'
    '                st.caption("\uff08\u672a\u6355\u83b7\u8fd4\u56de\u7ed3\u679c\uff09")\n'
    '            elif isinstance(tout, (dict, list)):\n'
    '                st.json(tout)\n'
    '            elif isinstance(tout, str):\n'
    '                try:\n'
    '                    parsed = json.loads(tout)\n'
    '                    if isinstance(parsed, (dict, list)):\n'
    '                        st.json(parsed)\n'
    '                    else:\n'
    '                        st.code(str(parsed))\n'
    '                except (json.JSONDecodeError, TypeError):\n'
    '                    if len(tout) > 6000:\n'
    '                        st.code(tout[:6000] + "\n\u2026(truncated)")\n'
    '                    else:\n'
    '                        st.code(tout)\n'
    '            else:\n'
    '                st.code(str(tout))\n'
    '        else:\n'
    '            _render_input_fallback(attrs, "output.value")\n'
)

src = src.replace(old, new, 1)
open(p, "w", encoding="utf-8", newline="\n").write(src)
print("Replaced; bytes:", len(src.encode("utf-8")))