# -*- coding: utf-8 -*-
"""Apply only Phase 5 (body wrap). Previous phases already applied."""
import sys
sys.stdout.reconfigure(encoding="utf-8")

p = r"D:\my-projects\agent-monitor\viewer.py"
src = open(p, encoding="utf-8").read()

# Use post-translation literals
old_body = (
    'col_tree, col_detail, col_meta = st.columns([1.1, 2.6, 1.3])\n'
    '\n'
    '\n'
    '# ===========================================================================\n'
    '# LEFT column - navigation tree\n'
    '# ===========================================================================\n'
    'with col_tree:\n'
    '    st.markdown(\n'
    '        f"#### \U0001F5C2 \u5bfc\u822a\u6811 "\n'
    '        f\'<span style="color:#9ca3af;font-size:11px;font-weight:400">\'\n'
    '        f\'\u00b7 {len(filtered_spans)} spans</span>\',\n'
    '        unsafe_allow_html=True,\n'
    '    )\n'
    '\n'
    '    def _select_only(sid: str) -> None:\n'
    '        st.session_state.selected_span = sid\n'
    '\n'
    '    def _toggle_expand(sid: str) -> None:\n'
    '        if sid in st.session_state.expanded_spans:\n'
    '            st.session_state.expanded_spans.discard(sid)\n'
    '        else:\n'
    '            st.session_state.expanded_spans.add(sid)\n'
    '\n'
    '    _render_tree(roots, children_map, depth=0)\n'
    '\n'
    '\n'
    '# ===========================================================================\n'
    '# CENTER column - detail panel (Run / Feedback / Metadata)\n'
    '# ===========================================================================\n'
    'with col_detail:\n'
    '    st.markdown("#### \U0001F50D Span \u8be6\u60c5")\n'
    '    _render_detail_panel(sel_spans, by_id_all={s["span_id"]: s for s in sel_spans})\n'
    '\n'
    '\n'
    '# ===========================================================================\n'
    '# RIGHT column - metadata indicator panel\n'
    '# ===========================================================================\n'
    'with col_meta:\n'
    '    st.markdown("#### \U0001F4CA \u5143\u6570\u636e\u9762\u677f")\n'
    '    _render_metadata_panel(kpi, sel_spans, by_id_all={s["span_id"]: s for s in sel_spans})\n'
)
assert old_body in src, "Phase 5 old_body not found"

new_body = (
    'if st.session_state.view_mode == "\u5217\u8868":\n'
    '    col_tree, col_detail, col_meta = st.columns([1.1, 2.6, 1.3])\n'
    '\n'
    '    # =======================================================================\n'
    '    # LEFT column - navigation tree\n'
    '    # =======================================================================\n'
    '    with col_tree:\n'
    '        st.markdown(\n'
    '            f"#### \U0001F5C2 \u5bfc\u822a\u6811 "\n'
    '            f\'<span style="color:#9ca3af;font-size:11px;font-weight:400">\'\n'
    '            f\'\u00b7 {len(filtered_spans)} spans</span>\',\n'
    '            unsafe_allow_html=True,\n'
    '        )\n'
    '\n'
    '        def _select_only(sid: str) -> None:\n'
    '            st.session_state.selected_span = sid\n'
    '\n'
    '        def _toggle_expand(sid: str) -> None:\n'
    '            if sid in st.session_state.expanded_spans:\n'
    '                st.session_state.expanded_spans.discard(sid)\n'
    '            else:\n'
    '                st.session_state.expanded_spans.add(sid)\n'
    '\n'
    '        _render_tree(roots, children_map, depth=0)\n'
    '\n'
    '    # =======================================================================\n'
    '    # CENTER column - detail panel (Run / Feedback / Metadata)\n'
    '    # =======================================================================\n'
    '    with col_detail:\n'
    '        st.markdown("#### \U0001F50D Span \u8be6\u60c5")\n'
    '        _render_detail_panel(sel_spans, by_id_all={s["span_id"]: s for s in sel_spans})\n'
    '\n'
    '    # =======================================================================\n'
    '    # RIGHT column - metadata indicator panel\n'
    '    # =======================================================================\n'
    '    with col_meta:\n'
    '        st.markdown("#### \U0001F4CA \u5143\u6570\u636e\u9762\u677f")\n'
    '        _render_metadata_panel(kpi, sel_spans, by_id_all={s["span_id"]: s for s in sel_spans})\n'
    '\n'
    'else:  # "\u6d41\u7a0b\u56fe" mode\n'
    '    _render_flowchart_mode(\n'
    '        sel_spans,\n'
    '        kpi,\n'
    '        all_by_id={s["span_id"]: s for s in sel_spans},\n'
    '    )\n'
)
src = src.replace(old_body, new_body, 1)
open(p, "w", encoding="utf-8", newline="\n").write(src)
print("Phase 5 done; bytes:", len(src.encode("utf-8")))