# -*- coding: utf-8 -*-
"""Final phase: build a comprehensive patcher using line-based surgery."""
import sys
sys.stdout.reconfigure(encoding="utf-8")

# Use a global helpers string defined as actual unicode chars
HELPERS = (
    "# ---------------------------------------------------------------------------\n"
    "# Flowchart mode (Mermaid) + click-to-zoom\n"
    "# ---------------------------------------------------------------------------\n"
    "_MERMAID_MAX_NODES = 80\n"
    "_NODE_LABEL_MAX_CHARS = 60\n"
    "\n"
    "\n"
    "def _mermaid_safe_id(sid):\n"
    "    return 'n_' + sid.replace('-', '_')\n"
    "\n"
    "\n"
    "def _mermaid_label(span):\n"
    "    attrs = span.get('attributes') or {}\n"
    "    kind = span_kind(attrs)\n"
    "    info = SPAN_KINDS.get(kind, SPAN_KINDS['UNKNOWN'])\n"
    "    icon = info[0]\n"
    "    name = _span_display_name(span)\n"
    "    name = re.sub(r'[\"\\\\#;|]', ' ', name).strip()\n"
    "    if len(name) > _NODE_LABEL_MAX_CHARS:\n"
    "        name = name[:_NODE_LABEL_MAX_CHARS - 1] + '...'\n"
    "    start_ns = int(span.get('start_time', 0))\n"
    "    end_ns = int(span.get('end_time', 0))\n"
    "    dur_ms = (end_ns - start_ns) / 1_000_000\n"
    "    dur = _format_duration_ms(dur_ms)\n"
    "    return f'<b>{icon} {name}</b><br/><small>{kind} &middot; {dur}</small>'\n"
    "\n"
    "\n"
    "def _build_mermaid(spans, *, focus=None, hops=2):\n"
    "    if not spans:\n"
    "        return 'flowchart TD\\n    empty[\\u3000\\uff08\\u65e0 span\\uff09\\u3000]'\n"
    "    spans_by_id = {s['span_id']: s for s in spans}\n"
    "    if focus and focus in spans_by_id:\n"
    "        visible = {focus}\n"
    "        up, down = {focus}, {focus}\n"
    "        for _ in range(hops):\n"
    "            new_up = set()\n"
    "            for sid in up:\n"
    "                pid = spans_by_id.get(sid, {}).get('parent_span_id')\n"
    "                if pid and pid in spans_by_id and pid not in visible:\n"
    "                    new_up.add(pid)\n"
    "            visible |= new_up\n"
    "            up = new_up\n"
    "            new_down = set()\n"
    "            for sid in down:\n"
    "                for s in spans:\n"
    "                    if s.get('parent_span_id') == sid and s['span_id'] not in visible:\n"
    "                        new_down.add(s['span_id'])\n"
    "            visible |= new_down\n"
    "            down = new_down\n"
    "    else:\n"
    "        visible = {s['span_id'] for s in spans}\n"
    "    visible_spans = [s for s in spans if s['span_id'] in visible]\n"
    "    if len(visible_spans) > _MERMAID_MAX_NODES and not focus:\n"
    "        return (\n"
    "            'flowchart TD\\n'\n"
    "            '    root[<\\u3000\\u5171 ' + str(len(spans)) + ' \\u4e2a span\\u3000<br/>'\n"
    "            \"<small>\\u8282\\u70b9\\u6570\\u8fc7\\u591a\\uff0c\\u8bf7\\u5207\\u56de \\u5217\\u8868 \\u6a21\\u5f0f\\u67e5\\u770b</small>]\\n\"\n"
    "            '    classDef root fill:#4b5563,color:#fff,stroke:#1f2937;\\n'\n"
    "            '    class root root;'\n"
    "        )\n"
    "    visible_spans.sort(key=lambda s: int(s.get('start_time', 0)))\n"
    "    starts = [int(s.get('start_time', 0)) for s in visible_spans]\n"
    "    min_start = min(starts) if starts else 0\n"
    "    out = ['flowchart TD']\n"
    "    out.append('    classDef llm       fill:#1d4ed8,color:#fff,stroke:#1e3a8a,stroke-width:1px;')\n"
    "    out.append('    classDef chain     fill:#065f46,color:#fff,stroke:#064e3b,stroke-width:1px;')\n"
    "    out.append('    classDef tool      fill:#b45309,color:#fff,stroke:#7c2d12,stroke-width:1px;')\n"
    "    out.append('    classDef agent     fill:#a16207,color:#fff,stroke:#713f12,stroke-width:1px;')\n"
    "    out.append('    classDef retriever fill:#7e22ce,color:#fff,stroke:#581c87,stroke-width:1px;')\n"
    "    out.append('    classDef embedding fill:#0e7490,color:#fff,stroke:#164e63,stroke-width:1px;')\n"
    "    out.append('    classDef reranker  fill:#6d28d9,color:#fff,stroke:#4c1d95,stroke-width:1px;')\n"
    "    out.append('    classDef prompt    fill:#3f6212,color:#fff,stroke:#365314,stroke-width:1px;')\n"
    "    out.append('    classDef parser    fill:#4b5563,color:#fff,stroke:#1f2937,stroke-width:1px;')\n"
    "    out.append('    classDef evaluator fill:#a8a29e,color:#1c1917,stroke:#78716c,stroke-width:1px;')\n"
    "    out.append('    classDef guardrail fill:#b91c1c,color:#fff,stroke:#7f1d1d,stroke-width:1px;')\n"
    "    out.append('    classDef unknown   fill:#6b7280,color:#fff,stroke:#374151,stroke-width:1px;')\n"
    "    out.append('    classDef error     stroke:#ef4444,stroke-width:2px,color:#fff;')\n"
    "    out.append('    classDef focus     stroke:#facc15,stroke-width:3px;')\n"
    "    out.append('    linkStyle default stroke:#64748b,stroke-width:1px;')\n"
    "    children_by_parent = {}\n"
    "    for s in visible_spans:\n"
    "        pid = s.get('parent_span_id')\n"
    "        if pid and pid in visible:\n"
    "            children_by_parent.setdefault(pid, []).append(s)\n"
    "    _handled_parents = set()\n"
    "    for span in visible_spans:\n"
    "        sid = span['span_id']\n"
    "        nid = _mermaid_safe_id(sid)\n"
    "        kind = span_kind(span.get('attributes') or {})\n"
    "        kind_class = kind.lower() if kind in SPAN_KINDS else 'unknown'\n"
    "        cls = [kind_class]\n"
    "        if str(span.get('status', '')).upper() == 'ERROR':\n"
    "            cls.append('error')\n"
    "        if sid == focus:\n"
    "            cls.append('focus')\n"
    "        start_ns = int(span.get('start_time', 0))\n"
    "        offset_ms = int((start_ns - min_start) / 1_000_000)\n"
    "        label = _mermaid_label(span)\n"
    "        full_label = f\"{label}<br/><small>t+{offset_ms}ms</small>\"\n"
    "        safe = re.sub(r'[\"\\\\#;|]', ' ', full_label).strip()\n"
    "        out.append(f'    {nid}[\"{safe}\"]')\n"
    "        out.append(f'    class {nid} {\",\".join(cls)};')\n"
    "    for parent_id, kids in children_by_parent.items():\n"
    "        if len(kids) < 2:\n"
    "            continue\n"
    "        sorted_kids = sorted(kids, key=lambda s: int(s.get('start_time', 0)))\n"
    "        n_kids = len(sorted_kids)\n"
    "        all_sequential = True\n"
    "        for i in range(n_kids - 1):\n"
    "            prev_end = int(sorted_kids[i].get('end_time', 0))\n"
    "            next_start = int(sorted_kids[i + 1].get('start_time', 0))\n"
    "            if next_start < prev_end:\n"
    "                all_sequential = False\n"
    "                break\n"
    "        pnid = _mermaid_safe_id(parent_id)\n"
    "        if all_sequential:\n"
    "            _handled_parents.add(parent_id)\n"
    "            first_id = _mermaid_safe_id(sorted_kids[0]['span_id'])\n"
    "            out.append(f'    {pnid} --> {first_id}')\n"
    "            for i in range(n_kids - 1):\n"
    "                a = _mermaid_safe_id(sorted_kids[i]['span_id'])\n"
    "                b = _mermaid_safe_id(sorted_kids[i + 1]['span_id'])\n"
    "                out.append(f'    {a} --> {b}')\n"
    "        else:\n"
    "            _handled_parents.add(parent_id)\n"
    "            out.append('    subgraph SG_' + pnid + '[\"\\u5e76\\u884c\\u5206\\u652f\"]')\n"
    "            out.append('    direction LR')\n"
    "            for k in sorted_kids:\n"
    "                out.append(f\"        {_mermaid_safe_id(k['span_id'])}\")\n"
    "            out.append('    end')\n"
    "            for k in sorted_kids:\n"
    "                out.append(f'    {pnid} --> {_mermaid_safe_id(k[\"span_id\"])}')\n"
    "    for span in visible_spans:\n"
    "        pid = span.get('parent_span_id')\n"
    "        if pid and pid in visible and pid not in _handled_parents:\n"
    "            out.append(f'    {_mermaid_safe_id(pid)} --> {_mermaid_safe_id(span[\"span_id\"])}')\n"
    "    for span in visible_spans:\n"
    "        nid = _mermaid_safe_id(span['span_id'])\n"
    "        out.append(f'    click {nid} focusSpan')\n"
    "    return '\\n'.join(out)\n"
    "\n"
    "\n"
    "def _render_mermaid_html(src, *, height=620, key_prefix='m'):\n"
    "    js_src = src.replace('\\\\', '\\\\\\\\').replace('`', '\\\\`').replace('${', '\\\\${')\n"
    "    html_doc = (\n"
    "        '<!DOCTYPE html>\\n<html><head><meta charset=\"utf-8\">\\n<style>\\n'\n"
    "        'body { margin:0; padding:8px; background:transparent; color:#e5e7eb; font-family:ui-system,system-ui,sans-serif; }\\n'\n"
    "        '.mermaid { background:rgba(255,255,255,0.02); border-radius:8px; padding:8px; overflow-x:auto; }\\n'\n"
    "        '.node { cursor:pointer; }\\n'\n"
    "        '.node:hover rect, .node:hover polygon { filter:brightness(1.25); }\\n'\n"
    "        '</style>\\n'\n"
    "        '<script src=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js\"></script>\\n'\n"
    "        '</head><body>\\n'\n"
    "        \"<div class='mermaid' id='m_\" + key_prefix + \"'>\\n\"\n"
    "        + js_src + '\\n'\n"
    "        \"</div>\\n<script>\\n\"\n"
    "        \"window.focusSpan = function(nodeId) {\\n\"\n"
    "        \"  var spanId = (nodeId || '').replace(/^n_/, '').replace(/_/g, '-');\\n\"\n"
    "        \"  if (!spanId) return;\\n\"\n"
    "        \"  var url = new URL(window.top.location.href);\\n\"\n"
    "        \"  url.searchParams.set('focus', spanId);\\n\"\n"
    "        \"  try { window.top.location.href = url.toString(); }\\n\"\n"
    "        \"  catch(e1) { try { window.parent.location.href = url.toString(); } catch(e2) { window.location.href = url.toString(); } }\\n\"\n"
    "        \"};\\n\"\n"
    "        \"mermaid.initialize({ startOnLoad:true, theme:'dark', themeVariables:{ background:'#0f172a', primaryColor:'#1e293b', primaryTextColor:'#e5e7eb', primaryBorderColor:'#334155', lineColor:'#64748b', fontFamily:'ui-system,system-ui,sans-serif' }, flowchart:{ curve:'basis', htmlLabels:true, useMaxWidth:true }, securityLevel:'loose' })\\n\"\n"
    "        \".then(function() { document.querySelectorAll('.mermaid .node').forEach(function(node) { node.addEventListener('click', function() { var id = node.id || (node.querySelector('[id]') ? node.querySelector('[id]').id : ''); var m = id.match(/n_[A-Za-z0-9_]+/); if (m) window.focusSpan(m[0]); }); }); });\\n\"\n"
    "        \"</script>\\n</body></html>\"\n"
    "    )\n"
    "    st.components.v1.html(html_doc, height=height, scrolling=True)\n"
    "\n"
    "\n"
    "def _render_flowchart_mode(sel_spans, kpi, all_by_id):\n"
    "    _url_trace = st.query_params.get('trace')\n"
    "    if _url_trace and _url_trace in traces:\n"
    "        if st.session_state.selected_trace != _url_trace:\n"
    "            st.session_state.selected_trace = _url_trace\n"
    "            sel_spans = traces[_url_trace]\n"
    "            all_by_id = {s['span_id']: s for s in sel_spans}\n"
    "            kpi = _aggregate_kpi(sel_spans)\n"
    "    focus = st.query_params.get('focus')\n"
    "    col_left, col_center, col_right = st.columns([1.1, 2.5, 1.3])\n"
    "    with col_left:\n"
    "        _render_trace_cards_list()\n"
    "    with col_center:\n"
    "        _render_flowchart_center(sel_spans)\n"
    "    with col_right:\n"
    "        _render_detail_column(sel_spans, all_by_id, focus)\n"
    "\n"
    "\n"
    "def _render_trace_cards_list():\n"
    "    st.markdown('#### \\U0001F4CB Traces')\n"
    "    if not traces:\n"
    "        st.caption('\\u8fd8\\u6ca1\\u6709 trace\\u3002\\u8bf7\\u8fd0\\u884c agent \\u540e\\u5237\\u65b0\\u3002')\n"
    "        return\n"
    "    cur_tid = st.session_state.selected_trace\n"
    "    sorted_tids = sorted(traces.keys(), key=_trace_start_ns)\n"
    "    for tid in sorted_tids:\n"
    "        row = _fmt_trace_option(tid)\n"
    "        is_cur = (tid == cur_tid)\n"
    "        btn_type = 'primary' if is_cur else 'secondary'\n"
    "        active_cls = ' trace-card-active' if is_cur else ''\n"
    "        st.markdown(f'<div class=\"trace-card{active_cls}\">', unsafe_allow_html=True)\n"
    "        st.button(\n"
    "            row,\n"
    "            key=f'trace_card_{tid}',\n"
    "            type=btn_type,\n"
    "            use_container_width=True,\n"
    "            on_click=_select_trace,\n"
    "            args=(tid,),\n"
    "        )\n"
    "        st.markdown('</div>', unsafe_allow_html=True)\n"
    "\n"
    "\n"
    "def _render_flowchart_center(sel_spans):\n"
    "    st.markdown('#### \\U0001F500 Agent \\u6d41\\u7a0b\\u56fe')\n"
    "    st.caption(\n"
    "        f'\\u5171 {len(sel_spans)} \\u4e2a span\\u3002\\u70b9\\u51fb\\u8282\\u70b9\\u67e5\\u770b\\u8be6\\u60c5\\uff1b\\u4e0a\\u65b9\\u4e3a\\u8d77\\u59cb\\u65f6\\u95f4\\u6700\\u65e9\\u7684\\u8282\\u70b9\\u3002'\n"
    "    )\n"
    "    _render_mermaid_html(_build_mermaid(sel_spans, focus=None), height=720, key_prefix='explorer')\n"
    "\n"
    "\n"
    "def _render_detail_column(sel_spans, all_by_id, focus):\n"
    "    st.markdown('#### \\U0001F50D Span \\u8be6\\u60c5')\n"
    "    if focus and focus in all_by_id:\n"
    "        if st.button('\\u2190 \\u8fd4\\u56de\\u5168\\u8c8c', key='back_to_overview'):\n"
    "            _clear_focus()\n"
    "        st.session_state.selected_span = focus\n"
    "    elif st.session_state.selected_span and st.session_state.selected_span in all_by_id:\n"
    "        pass\n"
    "    else:\n"
    "        roots = [s for s in sel_spans if not s.get('parent_span_id')]\n"
    "        if roots:\n"
    "            st.session_state.selected_span = roots[0]['span_id']\n"
    "    _render_detail_panel(sel_spans, by_id_all=all_by_id)\n"
    "    if focus and focus not in all_by_id:\n"
    "        _clear_focus()\n"
    "\n"
    "\n"
    "def _jump_to_span(span_id):\n"
    "    st.query_params['focus'] = span_id\n"
    "    st.rerun()\n"
    "\n"
    "\n"
    "def _clear_focus():\n"
    "    if 'focus' in st.query_params:\n"
    "        del st.query_params['focus']\n"
    "    st.rerun()\n"
    "\n"
    "\n"
    "def _select_trace(tid):\n"
    "    st.session_state.selected_trace = tid\n"
    "    if 'focus' in st.query_params:\n"
    "        del st.query_params['focus']\n"
    "\n"
    "\n"
    "def _trace_start_ns(tid):\n"
    "    spans = traces.get(tid) or []\n"
    "    if not spans:\n"
    "        return 0\n"
    "    return min(int(s.get('start_time', 0)) for s in spans)\n"
    "\n"
    "\n"
)
HELPERS_LINES = HELPERS.splitlines()
print(f"Helpers total lines: {len(HELPERS_LINES)}")


# Now read viewer.py
p = r"D:\my-projects\agent-monitor\viewer.py"
with open(p, encoding="utf-8") as f:
    lines = f.read().splitlines(keepends=False)


# Find anchors
left_tree_line = None
for i, l in enumerate(lines):
    if "LEFT tree renderer" in l:
        left_tree_line = i + 1
        break
assert left_tree_line, "left tree section not found"
print(f"left_tree_line: {left_tree_line}")


# Insert helpers BEFORE "# LEFT tree renderer" line
# We insert at line (left_tree_line - 1) so the helpers come first, then the existing comment
lines[left_tree_line - 1:left_tree_line - 1] = HELPERS_LINES
print(f"Inserted {len(HELPERS_LINES)} helper lines before L{left_tree_line}")

# Also need to find a marker for "Build filtered span list" to insert view-mode switcher
build_filtered_line = None
for i, l in enumerate(lines):
    if l.startswith("# Build filtered span list"):
        build_filtered_line = i + 1
        break
assert build_filtered_line, "build filtered anchor not found"

RADIO = [
    "",
    "# ---------------------------------------------------------------------------",
    "# View-mode switcher (TEMPORARY - will be removed in list-mode cleanup)",
    "# ---------------------------------------------------------------------------",
    "st.session_state.setdefault('view_mode', '\u5217\u8868')",
    "_view_opts = ['\u5217\u8868', '\u6d41\u7a0b\u56fe']",
    "_view_idx = _view_opts.index(st.session_state.view_mode) if st.session_state.view_mode in _view_opts else 0",
    "st.radio(",
    "    '\u89c6\u56fe\u6a21\u5f0f',",
    "    options=_view_opts,",
    "    index=_view_idx,",
    "    horizontal=True,",
    "    key='view_mode',",
    "    label_visibility='collapsed',",
    ")",
    "",
]
lines[build_filtered_line - 1:build_filtered_line - 1] = RADIO
print(f"Inserted radio before L{build_filtered_line}")


# Save
with open(p, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print(f"After helpers+radio: {len(lines)} lines")