# -*- coding: utf-8 -*-
"""Phase 3-8: line-based major structural changes.

Apply in REVERSE order: highest line first to avoid index shifts.
"""
import sys
sys.stdout.reconfigure(encoding="utf-8")

p = r"D:\my-projects\agent-monitor\viewer.py"
with open(p, encoding="utf-8") as f:
    lines = f.read().splitlines(keepends=False)
print("Starting with lines:", len(lines))


def show_anchors():
    for i, l in enumerate(lines):
        if any(needle in l for needle in [
            "LEFT tree renderer", "def _render_tree(",
            "def _render_metadata_panel(", "def _render_run_tab(",
            "def _render_input_fallback(", "def _render_msg(role: str, content: object)",
            "Input block (collapsible)", "Output block (collapsible)",
            "Build filtered span list", "col_tree, col_detail, col_meta = st.columns",
            "3-column body", "expanded_spans", "st.session_state.setdefault",
            'if st.session_state.view_mode =='
        ]):
            print("  L" + str(i + 1) + ": " + l[:60].encode("ascii", "replace").decode("ascii"))


# === Step 11: remove list mode (apply LAST but plan line nums NOW) ===
# We need to find these line numbers:
# - view_mode body check
# - col_tree = st.columns
# - 3-column body
# - _render_tree def
# - _render_metadata_panel def
# - expanded_spans init
view_mode_endif = None
col_tree_line = None
three_col_body = None
render_tree_line = None
render_metadata_line = None
expanded_spans_line = None
for i, l in enumerate(lines):
    if "if st.session_state.view_mode ==" in l and view_mode_endif is None:
        view_mode_endif = i + 1
    if "col_tree, col_detail, col_meta = st.columns" in l and col_tree_line is None:
        col_tree_line = i + 1
    if "3-column body" in l and three_col_body is None:
        three_col_body = i + 1
    if l.startswith("def _render_tree(") and render_tree_line is None:
        render_tree_line = i + 1
    if l.startswith("def _render_metadata_panel(") and render_metadata_line is None:
        render_metadata_line = i + 1
    if 'st.session_state.setdefault("expanded_spans"' in l and expanded_spans_line is None:
        expanded_spans_line = i + 1

print(f"view_mode_endif: {view_mode_endif}, col_tree_line: {col_tree_line}")
print(f"three_col_body: {three_col_body}, render_tree: {render_tree_line}")
print(f"render_metadata: {render_metadata_line}, expanded_spans: {expanded_spans_line}")


# === Define all transformations ===

# Step 4: Flowchart helpers (insert before L1067)
helpers = []
helpers.append("# ---------------------------------------------------------------------------")
helpers.append("# Flowchart mode (Mermaid) + click-to-zoom")
helpers.append("# ---------------------------------------------------------------------------")
helpers.append("_MERMAID_MAX_NODES = 80")
helpers.append("_NODE_LABEL_MAX_CHARS = 60")
helpers.append("")
helpers.append("")
helpers.append("def _mermaid_safe_id(sid):")
helpers.append("    return 'n_' + sid.replace('-', '_')")
helpers.append("")
helpers.append("")
helpers.append("def _mermaid_label(span):")
helpers.append("    attrs = span.get('attributes') or {}")
helpers.append("    kind = span_kind(attrs)")
helpers.append("    info = SPAN_KINDS.get(kind, SPAN_KINDS['UNKNOWN'])")
helpers.append("    icon = info[0]")
helpers.append("    name = _span_display_name(span)")
helpers.append("    name = re.sub(r'[\\\"\\\\#;|]', ' ', name).strip()")
helpers.append("    if len(name) > _NODE_LABEL_MAX_CHARS:")
helpers.append("        name = name[:_NODE_LABEL_MAX_CHARS - 1] + '...'")
helpers.append("    start_ns = int(span.get('start_time', 0))")
helpers.append("    end_ns = int(span.get('end_time', 0))")
helpers.append("    dur_ms = (end_ns - start_ns) / 1_000_000")
helpers.append("    dur = _format_duration_ms(dur_ms)")
helpers.append("    return f'<b>{icon} {name}</b><br/><small>{kind} &middot; {dur}</small>'")
helpers.append("")
helpers.append("")
helpers.append("def _build_mermaid(spans, *, focus=None, hops=2):")
helpers.append("    \"\"\"Build a Mermaid `flowchart TD` source.\"\"\"")
helpers.append("    if not spans:")
helpers.append("        return 'flowchart TD\\n    empty[\\u3000\\uff08\\u65e0 span\\uff09\\u3000]'")
helpers.append("    spans_by_id = {s['span_id']: s for s in spans}")
helpers.append("")
helpers.append("    if focus and focus in spans_by_id:")
helpers.append("        visible = {focus}")
helpers.append("        up, down = {focus}, {focus}")
helpers.append("        for _ in range(hops):")
helpers.append("            new_up = set()")
helpers.append("            for sid in up:")
helpers.append("                pid = spans_by_id.get(sid, {}).get('parent_span_id')")
helpers.append("                if pid and pid in spans_by_id and pid not in visible:")
helpers.append("                    new_up.add(pid)")
helpers.append("            visible |= new_up")
helpers.append("            up = new_up")
helpers.append("            new_down = set()")
helpers.append("            for sid in down:")
helpers.append("                for s in spans:")
helpers.append("                    if s.get('parent_span_id') == sid and s['span_id'] not in visible:")
helpers.append("                        new_down.add(s['span_id']")
helpers.append("            visible |= new_down")
helpers.append("            down = new_down")
helpers.append("    else:")
helpers.append("        visible = {s['span_id'] for s in spans}")
helpers.append("    visible_spans = [s for s in spans if s['span_id'] in visible]")
helpers.append("")
helpers.append("    if len(visible_spans) > _MERMAID_MAX_NODES and not focus:")
helpers.append("        return (")
helpers.append("            'flowchart TD\\n'")
helpers.append("            '    root[<\\u3000\\u5171 ' + str(len(spans)) + ' \\u4e2a span\\u3000<br/>'")
helpers.append("            \"<small>\\u8282\\u70b9\\u6570\\u8fc7\\u591a\\uff0c\\u8bf7\\u5207\\u56de \\u5217\\u8868 \\u6a21\\u5f0f\\u67e5\\u770b</small>]\\n\"")
helpers.append("            '    classDef root fill:#4b5563,color:#fff,stroke:#1f2937;\\n'")
helpers.append("            '    class root root;'")
helpers.append("        )")
helpers.append("")
helpers.append("    visible_spans.sort(key=lambda s: int(s.get('start_time', 0)))")
helpers.append("    starts = [int(s.get('start_time', 0)) for s in visible_spans]")
helpers.append("    min_start = min(starts) if starts else 0")
helpers.append("")
helpers.append("    out = ['flowchart TD']")
helpers.append("    out.append('    classDef llm       fill:#1d4ed8,color:#fff,stroke:#1e3a8a,stroke-width:1px;')")
helpers.append("    out.append('    classDef chain     fill:#065f46,color:#fff,stroke:#064e3b,stroke-width:1px;')")
helpers.append("    out.append('    classDef tool      fill:#b45309,color:#fff,stroke:#7c2d12,stroke-width:1px;')")
helpers.append("    out.append('    classDef agent     fill:#a16207,color:#fff,stroke:#713f12,stroke-width:1px;')")
helpers.append("    out.append('    classDef retriever fill:#7e22ce,color:#fff,stroke:#581c87,stroke-width:1px;')")
helpers.append("    out.append('    classDef embedding fill:#0e7490,color:#fff,stroke:#164e63,stroke-width:1px;')")
helpers.append("    out.append('    classDef reranker  fill:#6d28d9,color:#fff,stroke:#4c1d95,stroke-width:1px;')")
helpers.append("    out.append('    classDef prompt    fill:#3f6212,color:#fff,stroke:#365314,stroke-width:1px;')")
helpers.append("    out.append('    classDef parser    fill:#4b5563,color:#fff,stroke:#1f2937,stroke-width:1px;')")
helpers.append("    out.append('    classDef evaluator fill:#a8a29e,color:#1c1917,stroke:#78716c,stroke-width:1px;')")
helpers.append("    out.append('    classDef guardrail fill:#b91c1c,color:#fff,stroke:#7f1d1d,stroke-width:1px;')")
helpers.append("    out.append('    classDef unknown   fill:#6b7280,color:#fff,stroke:#374151,stroke-width:1px;')")
helpers.append("    out.append('    classDef error     stroke:#ef4444,stroke-width:2px,color:#fff;')")
helpers.append("    out.append('    classDef focus     stroke:#facc15,stroke-width:3px;')")
helpers.append("    out.append('    linkStyle default stroke:#64748b,stroke-width:1px;'")
helpers.append("")
helpers.append("    children_by_parent = {}")
helpers.append("    for s in visible_spans:")
helpers.append("        pid = s.get('parent_span_id')")
helpers.append("        if pid and pid in visible:")
helpers.append("            children_by_parent.setdefault(pid, []).append(s)")
helpers.append("")
helpers.append("    _handled_parents = set()")
helpers.append("")
helpers.append("    for span in visible_spans:")
helpers.append("        sid = span['span_id']")
helpers.append("        nid = _mermaid_safe_id(sid)")
helpers.append("        kind = span_kind(span.get('attributes') or {})")
helpers.append("        kind_class = kind.lower() if kind in SPAN_KINDS else 'unknown'")
helpers.append("        cls = [kind_class]")
helpers.append("        if str(span.get('status', '')).upper() == 'ERROR':")
helpers.append("            cls.append('error')")
helpers.append("        if sid == focus:")
helpers.append("            cls.append('focus')")
helpers.append("        start_ns = int(span.get('start_time', 0))")
helpers.append("        offset_ms = int((start_ns - min_start) / 1_000_000)")
helpers.append("        label = _mermaid_label(span)")
helpers.append("        full_label = f\"{label}<br/><small>t+{offset_ms}ms</small>\"")
helpers.append("        safe = re.sub(r'[\\\"\\\\#;|]', ' ', full_label).strip()")
helpers.append("        out.append(f'    {nid}[\\\"{safe}\\\"]')")
helpers.append("        out.append(f'    class {nid} {\",\".join(cls)};')")
helpers.append("")
helpers.append("    for parent_id, kids in children_by_parent.items():")
helpers.append("        if len(kids) < 2:")
helpers.append("            continue")
helpers.append("        sorted_kids = sorted(kids, key=lambda s: int(s.get('start_time', 0)))")
helpers.append("        n_kids = len(sorted_kids)")
helpers.append("        all_sequential = True")
helpers.append("        for i in range(n_kids - 1):")
helpers.append("            prev_end = int(sorted_kids[i].get('end_time', 0))")
helpers.append("            next_start = int(sorted_kids[i + 1].get('start_time', 0))")
helpers.append("            if next_start < prev_end:")
helpers.append("                all_sequential = False")
helpers.append("                break")
helpers.append("        pnid = _mermaid_safe_id(parent_id)")
helpers.append("        if all_sequential:")
helpers.append("            _handled_parents.add(parent_id)")
helpers.append("            first_id = _mermaid_safe_id(sorted_kids[0]['span_id'])")
helpers.append("            out.append(f'    {pnid} --> {first_id}')")
helpers.append("            for i in range(n_kids - 1):")
helpers.append("                a = _mermaid_safe_id(sorted_kids[i]['span_id'])")
helpers.append("                b = _mermaid_safe_id(sorted_kids[i + 1]['span_id'])")
helpers.append("                out.append(f'    {a} --> {b}')")
helpers.append("        else:")
helpers.append("            _handled_parents.add(parent_id)")
helpers.append("            out.append('    subgraph SG_' + pnid + '[\"\\u5e76\\u884c\\u5206\\u652f\"]')")
helpers.append("            out.append('    direction LR')")
helpers.append("            for k in sorted_kids:")
helpers.append("                out.append(f\"        {_mermaid_safe_id(k['span_id'])}\")")
helpers.append("            out.append('    end')")
helpers.append("            for k in sorted_kids:")
helpers.append("                out.append(f'    {pnid} --> {_mermaid_safe_id(k[\"span_id\"])}')")
helpers.append("")
helpers.append("    for span in visible_spans:")
helpers.append("        pid = span.get('parent_span_id')")
helpers.append("        if pid and pid in visible and pid not in _handled_parents:")
helpers.append("            out.append(f'    {_mermaid_safe_id(pid)} --> {_mermaid_safe_id(span[\"span_id\"])}')")
helpers.append("")
helpers.append("    for span in visible_spans:")
helpers.append("        nid = _mermaid_safe_id(span['span_id'])")
helpers.append("        out.append(f'    click {nid} focusSpan')")
helpers.append("")
helpers.append("    return '\\n'.join(out)")
helpers.append("")
helpers.append("")
helpers.append("def _render_mermaid_html(src, *, height=620, key_prefix='m'):")
helpers.append("    \"\"\"Render Mermaid inside an iframe. Mermaid click + DOM click.\"\"\"")
helpers.append("    js_src = (")
helpers.append("        src.replace('\\\\\\\\', '\\\\\\\\\\\\\\\\')")
helpers.append("           .replace('`', '\\\\\\\\`')")
helpers.append("           .replace('${', '\\\\\\\\${')")
helpers.append("    )")
helpers.append("    html_doc = (")
helpers.append("        '<!DOCTYPE html>\\n'")
helpers.append("        '<html><head><meta charset=\"utf-8\">\\n'")
helpers.append("        '<style>\\n'")
helpers.append("        '  body { margin: 0; padding: 8px; background: transparent;\\n'")
helpers.append("        \"         color: #e5e7eb; font-family: ui-system, system-ui, sans-serif; }\\n\"")
helpers.append("        '  .mermaid { background: rgba(255,255,255,0.02); border-radius: 8px; padding: 8px; overflow-x: auto; }\\n'")
helpers.append("        '  .node { cursor: pointer; }\\n'")
helpers.append("        '  .node:hover rect, .node:hover polygon { filter: brightness(1.25); }\\n'")
helpers.append("        '</style>\\n'")
helpers.append("        '<script src=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js\"></script>\\n'")
helpers.append("        '</head><body>\\n'")
helpers.append("        \"<div class='mermaid' id='m_\" + key_prefix + \"'>\\n\"")
helpers.append("        + js_src + '\\n'")
helpers.append("        \"</div>\\n\"")
helpers.append("        \"<script>\\n\"")
helpers.append("        \"  window.focusSpan = function(nodeId) {\\n\"")
helpers.append("        \"    var spanId = (nodeId || \\\"\\\").replace(/^n_/, \\\"\\\").replace(/_/g, \\\"-\\\");\\n\"")
helpers.append("        \"    if (!spanId) return;\\n\"")
helpers.append("        \"    var url = new URL(window.top.location.href);\\n\"")
helpers.append("        \"    url.searchParams.set(\\\"focus\\\", spanId);\\n\"")
helpers.append("        \"    try { window.top.location.href = url.toString(); }\\n\"")
helpers.append("        \"    catch (e1) { try { window.parent.location.href = url.toString(); } catch (e2) { window.location.href = url.toString(); } }\\n\"")
helpers.append("        \"  };\\n\"")
helpers.append("        \"  mermaid.initialize({\\n\"")
helpers.append("        \"    startOnLoad: true,\\n\"")
helpers.append("        \"    theme: 'dark',\\n\"")
helpers.append("        \"    themeVariables: {\\n\"")
helpers.append("        \"      background: '#0f172a',\\n\"")
helpers.append("        \"      primaryColor: '#1e293b',\\n\"")
helpers.append("        \"      primaryTextColor: '#e5e7eb',\\n\"")
helpers.append("        \"      primaryBorderColor: '#334155',\\n\"")
helpers.append("        \"      lineColor: '#64748b',\\n\"")
helpers.append("        \"      fontFamily: 'ui-system, system-ui, sans-serif',\\n\"")
helpers.append("        \"    },\\n\"")
helpers.append("        \"    flowchart: { curve: 'basis', htmlLabels: true, useMaxWidth: true },\\n\"")
helpers.append("        \"    securityLevel: 'loose',\\n\"")
helpers.append("        \"  }).then(function() {\\n\"")
helpers.append("        \"    document.querySelectorAll('.mermaid .node').forEach(function(node) {\\n\"")
helpers.append("        \"      node.addEventListener('click', function() {\\n\"")
helpers.append("        \"        var id = node.id || (node.querySelector('[id]') ? node.querySelector('[id]').id : '');\\n\"")
helpers.append("        \"        var m = id.match(/n_[A-Za-z0-9_]+/);\\n\"")
helpers.append("        \"        if (m) window.focusSpan(m[0]);\\n\"")
helpers.append("        \"      });\\n\"")
helpers.append("        \"    });\\n\"")
helpers.append("        \"  });\\n\"")
helpers.append("        \"</script>\\n\"")
helpers.append("        \"</body></html>\"")
helpers.append("    )")
helpers.append("    st.components.v1.html(html_doc, height=height, scrolling=True)")
helpers.append("")
helpers.append("")
helpers.append("def _render_flowchart_mode(sel_spans, kpi, all_by_id):")
helpers.append("    \"\"\"3-column flowchart explorer: traces | mermaid TD | span detail.\"\"\"")
helpers.append("    _url_trace = st.query_params.get('trace')")
helpers.append("    if _url_trace and _url_trace in traces:")
helpers.append("        if st.session_state.selected_trace != _url_trace:")
helpers.append("            st.session_state.selected_trace = _url_trace")
helpers.append("            sel_spans = traces[_url_trace]")
helpers.append("            all_by_id = {s['span_id']: s for s in sel_spans}")
helpers.append("            kpi = _aggregate_kpi(sel_spans)")
helpers.append("    focus = st.query_params.get('focus')")
helpers.append("")
helpers.append("    col_left, col_center, col_right = st.columns([1.1, 2.5, 1.3])")
helpers.append("")
helpers.append("    with col_left:")
helpers.append("        _render_trace_cards_list()")
helpers.append("    with col_center:")
helpers.append("        _render_flowchart_center(sel_spans)")
helpers.append("    with col_right:")
helpers.append("        _render_detail_column(sel_spans, all_by_id, focus)")
helpers.append("")
helpers.append("")
helpers.append("def _render_trace_cards_list():")
helpers.append("    \"\"\"Left column: trace cards sorted by earliest start_time.\"\"\"")
helpers.append("    st.markdown('#### \\U0001F4CB Traces')")
helpers.append("    if not traces:")
helpers.append("        st.caption('\\u8fd8\\u6ca1\\u6709 trace\\u3002\\u8bf7\\u8fd0\\u884c agent \\u540e\\u5237\\u65b0\\u3002')")
helpers.append("        return")
helpers.append("    cur_tid = st.session_state.selected_trace")
helpers.append("    sorted_tids = sorted(traces.keys(), key=_trace_start_ns)")
helpers.append("    for tid in sorted_tids:")
helpers.append("        row = _fmt_trace_option(tid)")
helpers.append("        is_cur = (tid == cur_tid)")
helpers.append("        btn_type = 'primary' if is_cur else 'secondary'")
helpers.append("        active_cls = ' trace-card-active' if is_cur else ''")
helpers.append("        st.markdown(")
helpers.append("            f'<div class=\"trace-card{active_cls}\">',")
helpers.append("            unsafe_allow_html=True,")
helpers.append("        )")
helpers.append("        st.button(")
helpers.append("            row,")
helpers.append("            key=f'trace_card_{tid}',")
helpers.append("            type=btn_type,")
helpers.append("            use_container_width=True,")
helpers.append("            on_click=_select_trace,")
helpers.append("            args=(tid,),")
helpers.append("        )")
helpers.append("        st.markdown('</div>', unsafe_allow_html=True)")
helpers.append("")
helpers.append("")
helpers.append("def _render_flowchart_center(sel_spans):")
helpers.append("    \"\"\"Center column: TD flowchart.\"\"\"")
helpers.append("    st.markdown('#### \\U0001F500 Agent \\u6d41\\u7a0b\\u56fe')")
helpers.append("    st.caption(")
helpers.append("        f'\\u5171 {len(sel_spans)} \\u4e2a span\\u3002'")
helpers.append("        '\\u70b9\\u51fb\\u8282\\u70b9\\u67e5\\u770b\\u8be6\\u60c5\\uff1b'")
helpers.append("        '\\u4e0a\\u65b9\\u4e3a\\u8d77\\u59cb\\u65f6\\u95f4\\u6700\\u65e9\\u7684\\u8282\\u70b9\\u3002'")
helpers.append("    )")
helpers.append("    _render_mermaid_html(")
helpers.append("        _build_mermaid(sel_spans, focus=None),")
helpers.append("        height=720,")
helpers.append("        key_prefix='explorer',")
helpers.append("    )")
helpers.append("")
helpers.append("")
helpers.append("def _render_detail_column(sel_spans, all_by_id, focus):")
helpers.append("    \"\"\"Right column: span detail panel.\"\"\"")
helpers.append("    st.markdown('#### \\U0001F50D Span \\u8be6\\u60c5')")
helpers.append("    if focus and focus in all_by_id:")
helpers.append("        if st.button('\\u2190 \\u8fd4\\u56de\\u5168\\u8c8c', key='back_to_overview'):")
helpers.append("            _clear_focus()")
helpers.append("        st.session_state.selected_span = focus")
helpers.append("    elif st.session_state.selected_span and st.session_state.selected_span in all_by_id:")
helpers.append("        pass")
helpers.append("    else:")
helpers.append("        roots = [s for s in sel_spans if not s.get('parent_span_id')]")
helpers.append("        if roots:")
helpers.append("            st.session_state.selected_span = roots[0]['span_id']")
helpers.append("    _render_detail_panel(sel_spans, by_id_all=all_by_id)")
helpers.append("    if focus and focus not in all_by_id:")
helpers.append("        _clear_focus()")
helpers.append("")
helpers.append("")
helpers.append("def _jump_to_span(span_id):")
helpers.append("    \"\"\"Set focus query param.\"\"\"")
helpers.append("    st.query_params['focus'] = span_id")
helpers.append("    st.rerun()")
helpers.append("")
helpers.append("")
helpers.append("def _clear_focus():")
helpers.append("    \"\"\"Clear focus query param.\"\"\"")
helpers.append("    if 'focus' in st.query_params:")
helpers.append("        del st.query_params['focus']")
helpers.append("    st.rerun()")
helpers.append("")
helpers.append("")
helpers.append("def _select_trace(tid):")
helpers.append("    \"\"\"Switch the active trace; clear any stale focus.\"\"\"")
helpers.append("    st.session_state.selected_trace = tid")
helpers.append("    if 'focus' in st.query_params:")
helpers.append("        del st.query_params['focus']")
helpers.append("")
helpers.append("")
helpers.append("def _trace_start_ns(tid):")
helpers.append("    \"\"\"Earliest span start_time (ns) in the trace; 0 if empty.\"\"\"")
helpers.append("    spans = traces.get(tid) or []")
helpers.append("    if not spans:")
helpers.append("        return 0")
helpers.append("    return min(int(s.get('start_time', 0)) for s in spans)")
helpers.append("")
helpers.append("")

print(f"\nHelpers count: {len(helpers)} lines")