"""Generated by ``python -m agent_monitor init``.

Replace the placeholder in the ``monitor()`` block with a call to your agent.
"""
from pathlib import Path


def _load_dotenv(path: Path) -> None:
    import os

    if not path.is_file():
        return
    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ[key.strip()] = value.strip().strip('"').strip("'")


_load_dotenv(Path(__file__).parent / ".env")

from agent_monitor import monitor  # noqa: E402


SERVICE_NAME = "my-agent"
INSTRUMENTORS = __AGENT_MONITOR_FRAMEWORKS__

with monitor(
    service_name=SERVICE_NAME,
    auto_instrument=True,
    instrumentors=INSTRUMENTORS,
    exporter="jsonl",
):
    # Replace this placeholder with your agent's entry-point call.
    print(f"[{SERVICE_NAME}] edit instrument.py to call your agent.")
