"""Generated by ``python -m agent_monitor init``.

Two edits and you are tracing:

  1. point ``ROOT_SPAN`` (and ``SERVICE_NAME``) at your own project
  2. point the import below at your own agent entry point

Then run it:      ``python instrument.py``      -> ./latest_traces.jsonl
And watch it:     ``python -m agent_monitor view``
"""
from pathlib import Path


def _load_dotenv(path: Path) -> None:
    import os

    if not path.is_file():
        return
    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ[key.strip()] = value.strip().strip('"').strip("'")


_load_dotenv(Path(__file__).parent / ".env")

from agent_monitor import monitor  # noqa: E402
from opentelemetry.trace import Status, StatusCode  # noqa: E402


# --- edit me -----------------------------------------------------------------
SERVICE_NAME = "my-agent"        # the span's "service" in the viewer
INSTRUMENTORS = __AGENT_MONITOR_FRAMEWORKS__
# ROOT_SPAN is the label the viewer shows in the trace dropdown.
# Do not end it with run / agent / task / step / chain: the viewer strips those
# as generic suffixes and the label would collapse to a single word.
ROOT_SPAN = "handle_request"


with monitor(
    service_name=SERVICE_NAME,
    auto_instrument=True,
    instrumentors=INSTRUMENTORS,
    exporter="jsonl",        # -> ./latest_traces.jsonl, one JSON line per span
) as tracer:
    # (1) Import your entry point HERE: inside monitor(), so the OpenInference
    #     monkey-patches are already active when LangChain builds its objects,
    #     but OUTSIDE the root span, so import time is not counted as agent
    #     runtime. Keep your own module import-side-effect free for this to
    #     hold: anything that emits a span at import time would land in its
    #     own separate trace.
    try:
        from run import main
    except ImportError:
        print(f"[{SERVICE_NAME}] nothing to run yet -- edit instrument.py:")
        print("        - set ROOT_SPAN to your own trace name")
        print("        - import your entry point (this expects ./run.py with main())")
        raise SystemExit(0)

    # (2) One root span around the whole agent lifetime, so every child span
    #     (LLM / tool / retrieval ...) shares a single trace_id and the viewer
    #     shows one row instead of one row per call.
    #     kind=AGENT gives the span its agent icon; without it the viewer can
    #     only fall back to "UNKNOWN".
    with tracer.start_as_current_span(
        ROOT_SPAN,
        attributes={"openinference.span.kind": "AGENT"},
    ) as root:
        # Optional: fill the viewer's Input / Output panels.
        # root.set_attribute("input.value", "the user's question")
        result = main()  # noqa: F841 - kept for the optional line below
        # root.set_attribute("output.value", str(result)[:2000])
        # Mark the finished run as OK so the viewer shows a green check rather
        # than an hourglass. An exception skips this line, and OpenTelemetry
        # then records the error and sets ERROR status automatically.
        root.set_status(Status(StatusCode.OK))
